<?php

namespace frontend\modules\stores\models;

use Yii;

/**
 * This is the model class for table "cw_cpa_link".
 *
 * @property integer $id
 * @property integer $cpa_id
 * @property integer $stores_id
 * @property integer $affiliate_id
 * @property string $affiliate_link
 */
class CpaLink extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cw_cpa_link';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cpa_id', 'stores_id', 'affiliate_id', 'affiliate_link'], 'required'],
            [['cpa_id', 'stores_id', 'affiliate_id'], 'integer'],
            [['affiliate_link'], 'string', 'max' => 255],
            //[['cpa_id', 'stores_id', 'affiliate_id'], 'unique', 'targetAttribute' => ['cpa_id', 'stores_id', 'affiliate_id'], 'message' => 'The combination of Spa ID, Stores ID and Affiliate ID has already been taken.'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cpa_id' => 'Cpa ID',
            'stores_id' => 'Stores ID',
            'affiliate_id' => 'Affiliate ID',
            'affiliate_link' => 'Affiliate Link',
        ];
    }

  /**
   * магазин купона
   * @return \yii\db\ActiveQuery
   */
  public function getStore()
  {
    return Stores::findOne(['uid' => $this->stores_id]);
  }

  public function afterSave($insert, $changedAttributes)
  {
    if($insert && $this->cpa_id!=1 && empty($this->affiliate_id)) {
      $this::getDb()
        ->createCommand()
        ->update($this->tableName(), ['affiliate_id' => $this->id], ['id' => $this->id])
        ->execute();
      $this->affiliate_id = $this->id;
    }
    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
  }

  /**
   * магазин купона
   * @return \yii\db\ActiveQuery
   */
  public function getStore2()
  {
    return $this->hasOne(Stores::className(), ['uid' => 'stores_id']);
  }

  public function getCpa()
  {
    return $this->hasOne(Cpa::className(), ['id' => 'cpa_id']);
  }

  public function getStoreActions()
  {
    return $this->hasMany(StoresActions::className(), ['cpa_link_id' => 'id']);
  }

    /**
     * @param $store
     * @param bool $userId
     */
  public static function clickUrl($store, $userId = false, $subid = false)
  {
      $userId = $userId ? $userId : (Yii::$app->user->isGuest ? 0 : Yii::$app->user->id);
      $cpaLink = $store->cpaLink;


      if ($subid && !empty($cpaLink->cpa->sub_id_template)) {
          //формируем идентификатор пользователя по шаблону в cpa
          $userLink = str_replace('{{subid}}', $userId, $cpaLink->cpa->sub_id_template);
          $userLink = str_replace('{{sub_id2}}', $subid, $userLink);
      } else {
          //или только $userId
          $userLink = $userId;
      }

      if ($cpaLink && $cpaLink->affiliate_link &&
          !empty($cpaLink->cpa->name) &&
          isset(Cpa::$user_id_params[$cpaLink->cpa->name])) {
          //admitad shareasale sellaction
          $link = self::makeGotoLink(
              $cpaLink->affiliate_link,
              [Cpa::$user_id_params[$cpaLink->cpa->name] => $userLink]
          );
      } else if ($cpaLink && !empty($cpaLink->cpa->name) &&
          in_array($cpaLink->cpa->name, Cpa::$user_id_in_template) && $cpaLink->affiliate_link ) {
          //внешние подключения, cj.com - ссылка в виде шаблона в cpa->affiliate_link
          $link = self::makeOutstandLink($cpaLink->affiliate_link, ['subid' => $userLink]);
      } else if ($cpaLink && $cpaLink->affiliate_link) {
          //не опознано cpa  но affiliate_link имеется
          $link = self::makeGotoLink($cpaLink->affiliate_link,  ['subid' => $userLink]);
      } else {
          //нет ничего подставляем store->url
          $link = self::makeGotoLink($store->url,  ['subid' => $userLink]);
      }
      return $link;
  }

  public function beforeDelete()
  {
      //actions
      $storesActions = StoresActions::find()
          ->where(['cpa_link_id' => $this->id])
          ->all();
      foreach ($storesActions as $storesAction) {
          $storesAction->delete();
      }
      return parent::beforeDelete();
  }

    /**
     * @param $link
     * @param $params
     * @return string
     */
    public static function makeGotoLink($link, $params)
    {
        if (!$link) {
            return '';
        }
        if (empty($params)) {
            return $link;
        }

        if(strpos($link,"{{") && strpos($link,"}}")){
            $link=Yii::$app->TwigString->render(
                $link,
                $params
            );
        }else {
            $link .= (strpos($link, '?') === false) ? '?' : '&';
            $link .= http_build_query($params);
        }
        return $link;
    }

    /** cсылки для внешних cpa
     * @param $paramsOffset
     * @param array $params
     * @return mixed|string
     */
    protected static function makeOutstandLink($offset, $params = [])
    {
        $link=$offset;
        foreach ($params as $key => $value) {
            $link = str_replace('{{'.$key.'}}', $value, $link);
        }
        return $link;
    }
}
