<?php
namespace frontend\controllers;

use Yii;
use yii\web\View;
use yii\helpers\Url;

class SdView extends View
{
 public function init()
 {
   parent::init(); // TODO: Change the autogenerated stub
   $this->registerJs('54');
 }

  public function beforeRender($viewFile, $params)
  {
    if (!parent::beforeRender($viewFile, $params)){
      return false;
    };

    /*
    $url=Url::current();
    $script_version=Yii::$app->params['scriptVersion'];
    $path_scripts=Yii::$app->params['pathToScript'];

    $path=trim($url,'/');
    $dir=explode('/',$path);
    $dir=$dir[0];
    if(isset($path_scripts[$dir])){
      $path_script=$path_scripts[$dir];
    }else{
      $path_script=$path_scripts['default'];
    }

    /* //прописываем js
    if(isset($path_script['js'])){
      foreach ($path_script['js'] as $js ){
        $js=str_replace('{{script_version}}',$script_version,$js);
        $this->registerJs($js);
      }
    }

    //прописываем стили
    if(isset($path_script['css'])){
      foreach ($path_script['css'] as $css ){
        $css=str_replace('{{script_version}}',$script_version,$css);
        $this->css[]=$css;
      }
    }*/


    /*d(Url::home(true));
    d(Url::current());
    d($this);
    d($viewFile);
    d($params);*/
    return true;
  }
}