<?php

namespace frontend\modules\users\models;

use yii;
use yii\base\Model;
use frontend\modules\promo\models\Promo as DbPromo;

class Promo extends Model
{
  public $promo;
  public $form;
  public $reCaptcha;
  public $dbPromo;

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['promo'], 'required'],
      ['promo', 'trim'],
      ['promo', function ($attribute) {
        $query = DbPromo::find()->where(['name'=>$this->promo])->asArray();
        if ($this->form) {
            $query->andWhere(['on_form' => 1]);
        }
        $this->dbPromo = $query->one();
        if (!$this->dbPromo) {
            $this->addError($attribute, Yii::t('main', 'wrong_promocode'));
        }
      }],
      ['form', 'integer'],
      [['reCaptcha'], \himiklab\yii2\recaptcha\ReCaptchaValidator::className(),
          'uncheckedMessage'=> Yii::t('main', 'wrong_recaptcha'), 'on' => 'form'],
    ];
  }

  public function attributeLabels()
  {
    return [
      'promo' => Yii::t('main', 'promocode'),
      'reCaptcha' => Yii::t('main', 'recaptcha'),
    ];
  }

  public function beforeValidate()
  {
      if (Yii::$app->request->post('g-recaptcha-response')) {
          $this->reCaptcha = Yii::$app->request->post('g-recaptcha-response');
      }
      if ($this->form == 1) {
          $this->scenario = 'form';
      }
      return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }


  public function save()
  {
      Yii::$app->session->set('referrer_promo', $this->promo);
  }

}