<?php

namespace frontend\modules\users\models;

use yii;
use yii\base\Model;

class Promo extends Model
{
  public $promo;
  public $form;
  public $reCaptcha;

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      ['promo', 'required'],
      ['promo', 'trim'],
      ['promo', function ($attribute) {
        if ($this->form == 1) {
            if (!in_array($this->promo, $this->formPromos())) {
                $this->addError($attribute, Yii::t('main', 'wrong_promocode'));
            }
        } else {
            if (!in_array($this->promo, array_keys(Yii::$app->params['ref_promo']))) {
                $this->addError($attribute, Yii::t('main', 'wrong_promocode'));
            }
        }
      }],
      ['form', 'integer'],
      [['reCaptcha'], \himiklab\yii2\recaptcha\ReCaptchaValidator::className(),
          'uncheckedMessage'=> Yii::t('main', 'wrong_recaptcha'), 'on' => 'form'],
    ];
  }

  public function attributeLabels()
  {
    return [
      'promo' => Yii::t('main', 'promocode'),
      'reCaptcha' => Yii::t('main', 'recaptcha'),
    ];
  }

  public function beforeValidate()
  {
      if (Yii::$app->request->post('g-recaptcha-response')) {
          $this->reCaptcha = Yii::$app->request->post('g-recaptcha-response');
      }
      if ($this->form == 1) {
          $this->scenario = 'form';
      }
      return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }


    public function save()
  {
      Yii::$app->session->set('referrer_promo', $this->promo);
  }

  private function formPromos()
  {
    $result = [];
      foreach (Yii::$app->params['ref_promo'] as $key => $promo) {
        if (isset($promo['form']) && $promo['form'] == 1) {
            $result[] = $key;
        }
    }
    return $result;
  }


}