<?php
namespace frontend\modules\users\models;

use common\components\DataValidator;
use common\components\DomainValidator;
use yii\base\Model;
use yii\base\InvalidParamException;
use frontend\modules\users\models\Users;
use Yii;

/**
 * Password reset form
 */
class UserSetting extends Users
{

  public $old_password;
  public $new_password;
  public $r_new_password;

  private $_user;


  /**
   * @inheritdoc
   */
  public function rules()
  {

    return [
        ['name', 'trim'],
        [['email', 'name'], 'string', 'max' => 60],
        [['birthday'], DataValidator::className()],
        [['sex'], 'string', 'max' => 1],
        [['notice_email'], 'integer'],

        [['email', 'name', 'added'], 'required'],
        [['email'], 'email'],
        [['email'], 'unique', 'message' => Yii::t('account', 'save_settings_email_exists')],
        ['email', DomainValidator::className()],

//        [['old_password', 'new_password', 'r_new_password'], 'safe'],
//
//      //делаем обязательными новый пароль его ввод когда заполнили старый пароль дубль нового
//        ['new_password', 'required', 'when' => function ($model) {
//          return strlen($model->old_password) > 0 || strlen($model->r_new_password) > 0;
//        }, 'whenClient' => "function (attribute, value) {
//        return
//          $('#usersetting-old_password').val().length >0 ||
//          $('#usersetting-r_new_password').val().length >0;
//      }"],
//
//        ['old_password', 'required', 'when' => function ($model) {
//          return strlen($model->new_password) > 0 || strlen($model->r_new_password) > 0;
//        }, 'whenClient' => "function (attribute, value) {
//        return
//          $('#usersetting-new_password').val().length >0 ||
//          $('#usersetting-r_new_password').val().length >0;
//      }"],
//
//        ['r_new_password', 'required', 'when' => function ($model) {
//          return strlen($model->old_password) > 0 || strlen($model->new_password) > 0;
//        }, 'whenClient' => "function (attribute, value) {
//        return
//          $('#usersetting-old_password').val().length >0 ||
//          $('#usersetting-new_password').val().length >0;
//      }"],

        ['!new_photo', 'file', 'extensions' => 'jpeg', 'on' => ['insert', 'update']],
        [['new_photo'], 'image',
            'minHeight' => 500,
            'maxSize' => 2 * 1024 * 1024,
            'skipOnEmpty' => true
        ],
    ];
  }


  public function beforeValidate()
  {
    if (!empty($this->getDirtyAttributes(['email']))) {
      $this->email_verified = 0;
    }
    return parent::beforeValidate();
  }

  public function attributeLabels()
  {
    return array(
        'name' => Yii::t('account', 'user_name'),
    );
  }

  public function isAttributeRequired($attribute)
  {
    return parent::isAttributeRequired($attribute); // TODO: Change the autogenerated stub
  }

    /**
     * @param bool $insert
     * @param array $changedAttributes
     */
  public function afterSave($insert, $changedAttributes){
    parent::afterSave($insert, $changedAttributes);

      if (!empty($changedAttributes['email'])) {
        Yii::$app->session->addFlash(null, Yii::t('account', 'save_settings_need_verify_email') .
              '<br><a href="/account/sendverifyemail">' . Yii::t('common', 'confirm') . '</a>');
      }

  }
}
