<?php
namespace frontend\modules\users\models;

use yii\base\Model;
use yii\base\InvalidParamException;
use frontend\modules\users\models\Users;
use Yii;

/**
 * Password reset form
 */
class UserSetting extends Users
{

  public $old_password;
  public $new_password;
  public $r_new_password;

  private $_user;



  /**
   * @inheritdoc
   */
  public function rules()
  {

    return [
      ['name', 'trim'],
      [['email', 'name'], 'string', 'max' => 60],
      [['birthday'], 'safe'],
      [['sex'], 'string', 'max' => 1],
      [['notice_email'], 'integer'],

      [['email', 'name',  'added'], 'required'],
      [['email'], 'email'],
      [['email'], 'unique','message' => 'Данныей email принадлежит другому пользователю.'],

      [['old_password','new_password','r_new_password'], 'string'],
      [['old_password','new_password','r_new_password'], 'trim'],
      [['old_password','new_password','r_new_password'], 'string', 'max' => 60],
      [['old_password','new_password','r_new_password'], 'string', 'min' => 6],

      ['old_password', 'validatePassword'],

      ['r_new_password',
        'compare',
        'compareAttribute' => 'new_password',
        'message' => 'Введенные пароли не совпадают.'
      ],

      //делаем обязательными новый пароль его ввод когда заполнили старый пароль дубль нового
      ['new_password', 'required', 'when' => function ($model) {
        return strlen($model->old_password)>0 || strlen($model->r_new_password)>0;
      }, 'whenClient' => "function (attribute, value) {
        return 
          $('#usersetting-old_password').val().length >0 ||
          $('#usersetting-r_new_password').val().length >0;
      }"],

      ['old_password', 'required', 'when' => function ($model) {
        return strlen($model->new_password)>0 || strlen($model->r_new_password)>0;
      }, 'whenClient' => "function (attribute, value) {
        return 
          $('#usersetting-new_password').val().length >0 ||
          $('#usersetting-r_new_password').val().length >0;
      }"],

      ['r_new_password', 'required', 'when' => function ($model) {
        return strlen($model->old_password)>0 || strlen($model->new_password)>0;
      }, 'whenClient' => "function (attribute, value) {
        return 
          $('#usersetting-old_password').val().length >0 ||
          $('#usersetting-new_password').val().length >0;
      }"],

      ['!new_photo', 'file', 'extensions' => 'jpeg', 'on' => ['insert', 'update']],
      [['new_photo'], 'image',
        'minHeight' => 500,
        'maxSize' => 2 * 1024 * 1024,
        'skipOnEmpty' => true
      ],
    ];
  }

  public function validatePassword($old_password)
  {
    if (!Yii::$app->getSecurity()->validatePassword($this->old_password, $this->password)) {
      $this->addError('old_password', 'Старый пароль введен не верно.');
    }
  }

  public function attributeLabels() {
    return array(
      'name' => 'Имя',
      'old_password'=>'Старый пароль',
      'new_password'=>'Новый пароль',
      'r_new_password'=>'Новый пароль(повторно)',
    );
  }

  public function isAttributeRequired($attribute)
  {
    return parent::isAttributeRequired($attribute); // TODO: Change the autogenerated stub
  }
}
