<?php
namespace frontend\components;

use Yii;
use yii\web\View;
use yii\helpers\Url;
use app\modules\meta\models\Meta;

class SdView extends View
{
 public $h1;
 public $contentBD;

  public $user_id=false;
  public $user=[];
  public $balance=[];

 public function init()
 {
   parent::init(); // TODO: Change the autogenerated stub
   $this->registerJs('54');
 }

  public function beforeRender($viewFile, $params)
  {
    if (!parent::beforeRender($viewFile, $params)){
      return false;
    };

    if(!Yii::$app->user->isGuest){
      $this->user_id=Yii::$app->user->id;
      $user=Yii::$app->user->identity;
      $this->user=(array)$user->getIterator();
      $this->balance=$user->getBalabce();
    }

    $arr = $this->getPageMetadata();
    if (isset($arr['description'])) $this->metaTags[] = '<meta name="description" content="'.$arr['description'].'">';
    if (isset($arr['keywords'])) $this->metaTags[] = '<meta name="keywords" content="'.$arr['keywords'].'">';
    if (isset($arr['title'])) $this->title = $arr['title'];
    if (isset($arr['content'])) $this->contentBD = $arr['content'];
    if (isset($arr['h1'])) $this->h1 = $arr['h1'];

    return true;
  }

  /**
   * получение метаданных
   */
  private function getPageMetadata()
  {
    $page = Yii::$app->request->pathInfo;

    if($page=='affiliate-system'){
      $page='account/affiliate';
    };
    if ($page == '') $page = 'index';

    $page_meta = Meta::find()
        ->select(['title', 'description', 'keywords', 'h1', 'content'])
        ->where(['page' => $page])
        ->asArray()
        ->all();

      if (count($page_meta) > 0) {
        $page_meta = $page_meta[0];
      } else {
        $arr = explode('/',$page);
        $page = $arr[0].'/'.$arr[1];
        //прямого совпадения нет ищем по плейсхолдерам
        $mdataArray = Meta::find()
          ->select(['title', 'description', 'keywords', 'h1', 'content'])
          ->where(['like','page', $page.'%',false])
          ->OrderBy(['page'=>SORT_ASC])
          ->asArray()
          ->all();
          $page_meta = $mdataArray[0];
        }
    return $page_meta;
  }

}