<?php
namespace frontend\components;

use Yii;
use yii\web\View;
use yii\helpers\Url;
use app\modules\meta\models\Meta;

class SdView extends View
{
 public $h1;
 public $contentBD;

  public $user_id=false;
  public $user=[];
  public $balance=[];

 public function init()
 {
   parent::init(); // TODO: Change the autogenerated stub
   $this->registerJs('54');
 }

  public function beforeRender($viewFile, $params)
  {
   // ddd(Yii::$app->request->pathInfo);
    if (!parent::beforeRender($viewFile, $params)){
      return false;
    };

    if(!Yii::$app->user->isGuest){
      $this->user_id=Yii::$app->user->id;
      $user=Yii::$app->user->identity;
      $this->user=(array)$user->getIterator();
      $this->balance=$user->getBalabce();
    }

    $arr = $this->getPageMetadata();
    //ddd($this->params);
    //$this->metaTags = $this->getPageMetadata();
    if (isset($arr['description'])) $this->metaTags[] = '<meta name="description" content="'.$arr['description'].'">';
    if (isset($arr['keywords'])) $this->metaTags[] = '<meta name="keywords" content="'.$arr['keywords'].'">';
    if (isset($arr['title'])) $this->title = $arr['title'];
    if (isset($arr['content'])) $this->contentBD = $arr['content'];
    if (isset($arr['h1'])) $this->h1 = $arr['h1'];

    //Yii::$app->view->params['contentFromBD'] = $arr['content'];
    //$this->params['h1TagFromBD'] = $arr['h1'];

    return true;
  }

  /**
   * получение метаданных
   */
  private function getPageMetadata()
  {
    $page = Yii::$app->request->pathInfo;
    $cacheType = "metadata";
    $cacheName = "metadata_" . $page;

    if($page=='affiliate-system'){
      $page='account/affiliate';
    };
    if ($page == '') $page = 'index';
    $mdata = false;

    if ($mdata === false) {
      //вначале из базы
      $mdata = Meta::find()
        ->select(['title', 'description', 'keywords', 'h1', 'content'])
        ->where(['page' => $page])
        ->asArray()->all();
      //ddd($mdata);
      if (count($mdata) > 0) {
        $mdata = $mdata[0];
      } else {
        //прямого совпадения нет ищем по плейсхолдерам
        $mdataArray = Meta::find()
          ->select('*')
       //   ->select('LENGTH(`page`)', 'l')
          ->where(['like','page','%*%'])
          ->OrderBy(['page'=>SORT_ASC])
          ->all();
        foreach ($mdataArray as $mdataItem) {
          $noalias = explode('*', $mdataItem->page);
          $match = '/^' . str_replace('/', '\/', $noalias[0]) . '.*' .
            str_replace('/', '\/', (!empty($noalias[1]) ? $noalias[1] : '')) . '$/';
          if (preg_match($match, $page)) {
            $mdata = [
              'title' => $mdataItem->title,
              'description' => $mdataItem->description,
              'keywords' => $mdataItem->keywords,
              'h1' => $mdataItem->h1,
              'content' => $mdataItem->content,
            ];
            break;
          }
        }
       // if (!$mdata) {
          //если нет, то из настроек
      //    $mdata = \Cwcashback\Settings::call()->getSettings('metadata', $page);
       // }
      }

    //  if (\Cwcashback\Settings::call()->getSettings('env', 'cache')) {
      //  \Cwcashback\Memcache::addData(
        //  $cacheType,
          //$cacheName,
    //      $mdata,
      //    false,
        //  \Cwcashback\Settings::call()->getSettings('cachetime', 'month')
     //   );
     // }
    }
    return $mdata;
  }

}