var siteUrl = 'http://api.secretdiscounter.ru/';
//var siteUrl = 'http://sdapi/';
var frontUrl = 'https://secretdiscounter.com/';
var userUrl = 'account/notification';
var storesUrl = 'stores/data';
var userFavoriteUrl = 'account/favorites';
var couponUrl = 'coupons';
var storeActiveInterval = 30;//минут
var storePopupCloseInterval = 60;//минут
var storeActiveStorageName = 'secretdiscounter-extension-store-';// + store_route
var storePopupClosedStorageName = 'secretdiscounter-extension-popup-closed-store-';// + store_route
var debug = false;
