<?php

namespace frontend\modules\coupons\models;

use Yii;
use frontend\modules\stores\models\Stores;


/**
 * This is the model class for table "cw_coupons".
 *
 * @property integer $uid
 * @property integer $coupon_id
 * @property string $name
 * @property string $image
 * @property string $description
 * @property string $date_start
 * @property string $date_end
 * @property string $goto_link
 * @property string $promocode
 * @property integer $exclusive
 * @property integer $species
 * @property integer $visit
 * @property integer $store_id
 */
class Coupons extends \yii\db\ActiveRecord
{
  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'cw_coupons';
  }

  /**
   * @var string
   */
  public static $defaultSort = 'date_end';
  /**
   * Possible sorting options with titles and default value
   * @var array
   */
  public static $sortvars = [
    'visit' => ["title" => "Популярности", "title_mobile" => "По популярности"],
    'date_start' => ["title" => "Новизне", "title_mobile" => "По новизне"],
    'date_end' => ["title" => "Сроку действия", "title_mobile" => "По сроку действия", 'sort' => 'ASC'],
  ];

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['coupon_id', 'name', 'description', 'date_start', 'date_end', 'goto_link', 'promocode', 'exclusive', 'species'], 'required'],
      [['coupon_id', 'exclusive', 'species', 'visit', 'store_id'], 'integer'],
      [['description'], 'string'],
      [['date_start', 'date_end'], 'safe'],
      [['name', 'goto_link', 'promocode'], 'string', 'max' => 255],
      [['coupon_id'], 'unique'],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'uid' => 'Uid',
      'coupon_id' => 'Coupon ID',
      'name' => 'Name',
      'description' => 'Description',
      'date_start' => 'Date Start',
      'date_end' => 'Date End',
      'goto_link' => 'Goto Link',
      'promocode' => 'Promocode',
      'exclusive' => 'Exclusive',
      'species' => 'Species',
      'visit' => 'Visit',
      'store_id' => 'Store ID',
    ];
  }

  public function afterDelete()
  {
    parent::afterDelete(); // TODO: Change the autogenerated stub
    CouponsToCategories::deleteAll(['coupon_id' => $this->coupon_id]);
  }

  /**
   * магазин купона
   * @return \yii\db\ActiveQuery
   */
  public function getStore()
  {
    return $this->hasOne(Stores::className(), ['uid' => 'store_id']);
  }

  /**
   * Категории купона
   * @return $this
   */
  public function getCategories()
  {
    return $this->hasMany(CategoriesCoupons::className(), ['uid' => 'category_id'])
      ->viaTable('cw_coupons_to_categories', ['coupon_id' => 'coupon_id']);
  }

  /**
   * @return mixed
   */
  public static function getActiveCategoriesCoupons()
  {
    $cache = Yii::$app->cache;
    $categories = $cache->getOrSet('categories_coupons', function () {
      return CategoriesCoupons::find()
        ->from(CategoriesCoupons::tableName() . ' ccc')
        ->select(['ccc.name', 'ccc.uid', 'count(cct.coupon_id) as count'])
        ->innerJoin('cw_coupons_to_categories cct', "ccc.uid = cct.category_id")
        ->innerJoin(self::tableName() . ' cwc', 'cct.coupon_id = cwc.coupon_id')
        ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
        ->where(['cws.is_active' => 1])
        ->groupBy('cct.category_id')
        ->asArray()
        ->all();
    });
    return $categories;
  }

  /**
   * @return mixed
   */
  public static function getActiveStoresCoupons()
  {
    $cache = Yii::$app->cache;
    $categories = $cache->getOrSet('stores_coupons', function () {
      return self::find()
        ->from(self::tableName() . ' cwc')
        ->select(['cws.name', 'cws.uid', 'count(cwc.uid) as count'])
        ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
        ->where(['cws.is_active' => 1])
        ->groupBy('cwc.store_id')
        ->orderBy('cws.name ASC')
        ->asArray()
        ->all();
    });
    return $categories;
  }

  public static function activeCount()
  {
    $cache = Yii::$app->cache;
    $count = $cache->getOrSet('total_all_coupons', function () {
      return self::find()
        ->from(self::tableName() . ' cwc')
        ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
        ->where(['cws.is_active' => 1])
        ->count();
    });
    return $count;
  }
}
