<?php

namespace frontend\modules\coupons\models;

use common\components\Help;
use frontend\modules\stores\models\Cpa;
use yii;
use frontend\modules\stores\models\Stores;
use frontend\modules\stores\models\CategoriesStores;
use frontend\modules\stores\models\StoresCategoriesToCouponsCategories;
use frontend\modules\cache\models\Cache;
use frontend\modules\reviews\models\Reviews;


/**
 * This is the model class for table "cw_coupons".
 *
 * @property integer $uid
 * @property integer $coupon_id
 * @property string $name
 * @property string $image
 * @property string $description
 * @property string $date_start
 * @property string $date_end
 * @property string $goto_link
 * @property string $promocode
 * @property integer $exclusive
 * @property integer $species
 * @property integer $visit
 * @property integer $store_id
 */
class Coupons extends \yii\db\ActiveRecord
{
  const NEW_COUPONS_SUB_DAYS = 7;//Новые купоны дней до

    public $reviews_count;

  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'cw_coupons';
  }
  
  /**
   * @var string
   */
  public static $defaultSort = 'visit';
  /**
   * Possible sorting options with titles and default value
   * @var array
   */
  public static $sortvars = [
      'visit' => ["title" => "Популярности", "title_mobile" => "Популярности"],
      'date_start' => ["title" => "Новизне", "title_mobile" => "Новизне"],
      'date_end' => ["title" => "Сроку действия", "title_mobile" => "Сроку действия", 'order' => 'DESC'],
  ];

  public static function sortvars(){
      return [
          'visit' => [
              "title" => Yii::t('main','sort_by_rating'),
              "title_mobile" => Yii::t('main','sort_by_rating_mobile'),
          ],
          'date_start' => [
              "title" => Yii::t('main','sort_by_date'),
              "title_mobile" => Yii::t('main','sort_by_date_mobile')
          ],
          'date_end' => [
              "title" => Yii::t('main','sort_by_expire'),
              "title_mobile" => Yii::t('main','sort_by_expire_mobile'),
              'order' => 'DESC'
          ],
      ];
  }


  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
        [['coupon_id', 'name', 'date_start', 'date_end', 'exclusive', 'species'], 'required'],
        [['coupon_id', 'exclusive', 'species', 'visit', 'store_id','cpa_id'], 'integer'],
        [['description', 'promocode', 'language'], 'string'],
        [['description', 'promocode'], 'trim'],
        [['date_start', 'date_end'], 'safe'],
        [['name', 'goto_link', 'promocode'], 'string', 'max' => 255],
        [['coupon_id'], 'unique', 'targetAttribute' => ['store_id', 'coupon_id']],
        [['cpa_id'], 'exist', 'targetClass' => Cpa::className(), 'targetAttribute' => ['cpa_id' => 'id']],
    ];
  }

  public function beforeValidate()
  {
    $pv = parent::beforeValidate();
    if (strlen($this->name) > 0) {
      $this->name = str_replace('\n', '', $this->name);
      $this->name = str_replace(chr(13), '', $this->name);
      $this->name = str_replace(chr(10), '', $this->name);
      $this->name = preg_replace("/  +/", " ", $this->name);
      $this->name = trim($this->name);

      $cont_no_msk = null;
      preg_replace('/[^0-9a-zA-Zа-яёА-ЯЁ .!#$:+-=]/u', '', $this->name, -1, $cont_no_msk);
      //preg_replace('/[^,\p{Cyrillic}\p{Latin}]/ui', '', $this->name, -1, $cont_no_msk);
      $count_tot = strlen($this->name);
      if ($cont_no_msk > 0 && ($cont_no_msk / $count_tot) > 0.2) {
        $this->addError('name', "Много спец. символов или специфический язык");
        return false;
      }
    }

    if ($this->description) {
      $this->description = preg_replace("/  +/", " ", $this->description);
      $this->description = trim($this->description);
      $this->description = str_replace('\n', '', $this->description);
      $this->description = str_replace('
', '', $this->description);
    }

    return $pv; // TODO: Change the autogenerated stub
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
        'uid' => 'Uid',
        'coupon_id' => 'Coupon ID',
        'name' => 'Name',
        'description' => 'Description',
        'date_start' => 'Date Start',
        'date_end' => 'Date End',
        'goto_link' => 'Goto Link',
        'promocode' => 'Promocode',
        'exclusive' => 'Exclusive',
        'species' => 'Species',
        'visit' => 'Visit',
        'store_id' => 'Store ID',
        'storeName' => 'Магазин',
        'language' => 'Язык',
        'cpaName' => 'CPA',
        'reviews_count' => 'Отзывов'

    ];
  }

  public function afterDelete()
  {
    parent::afterDelete(); // TODO: Change the autogenerated stub
    CouponsToCategories::deleteAll(['coupon_id' => $this->coupon_id]);

    $this->clearCache();
  }

  /**
   * магазин купона
   * @return \yii\db\ActiveQuery
   */
  public function getStore()
  {
    return $this->hasOne(Stores::className(), ['uid' => 'store_id']);
  }

  public function getStoreName()
  {
    if ($this->store) {
      //return $this->store->name;
      return '<a href="/admin/stores/update?id=' . $this->store->uid . '">' . $this->store->name . ' (' . $this->store->uid . ')</a>';
    } else {
      return '';
    }
  }

  public function beforeSave($insert)
  {
    if ($this->promocode == 'НЕ НУЖЕН') $this->promocode = '';
    if ($this->promocode == 'NOT REQUIRED') $this->promocode = '';
    if ($this->promocode == 'Не нужен') $this->promocode = '';
    if ($this->promocode == 'Promo-code not required！') $this->promocode = '';
    if ($this->promocode == 'Промокод нужен!') $this->promocode = '';

    if ($this->language == null) {
        $this->language = Yii::$app->languageDetector->detect($this->description . $this->name);
    }

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  /**
   * Категории купона
   * @return $this
   */
  public function getCategories()
  {
    return $this->hasMany(CategoriesCoupons::className(), ['uid' => 'category_id'])
        ->viaTable('cw_coupons_to_categories', ['coupon_id' => 'uid']);
  }

    /** отзывы
     * @return yii\db\ActiveQuery
     */
  public function getReviews()
  {
      return $this->hasMany(Reviews::className(), ['coupon_id' => 'uid']);
  }

  /**
   * @return mixed
   */
  public static function getActiveCategoriesCoupons($where = [])
  {
    $languages = self::languagesArray();
    $cache = Yii::$app->cache;
    $language = Yii::$app->language  == Yii::$app->params['base_lang'] ? false : Yii::$app->language;
    $cacheName = 'categories_coupons' . ($language ? '_' . $language : '');
    if (!empty($where)) {
      foreach($where as $key => $value) {
        $cacheName .= ('_'.$key.'_'.$value);
      }
    }
    $dependencyName = 'catalog_coupons';
    $dependency = new yii\caching\DbDependency;
    $dependency->sql = 'select `last_update` from `cw_cache` where `name` = "' . $dependencyName . '"';
    $categories = $cache->getOrSet($cacheName, function () use ($languages, $where) {
      $categories =  CategoriesCoupons::translated(['uid', 'name', 'route'])
          ->addSelect(['count(cwctc.coupon_id) as count'])
          ->innerJoin('cw_coupons_to_categories cwctc', "cwcc.uid = cwctc.category_id")
          ->innerJoin(self::tableName() . ' cwc', 'cwctc.coupon_id = cwc.uid')
          ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
          //->where(['cws.is_active' => [0, 1]])
          ->where(['cws.is_active' => [1]])
          ->andWhere(['>', 'cwc.date_end', date('Y-m-d H:i:s', time())])
          ->groupBy('cwctc.category_id')
          ->asArray();
      if (!empty($languages)) {
          $categories->andWhere(['cwc.language' => $languages]);
      }
      if (!empty($where)) {
          $categories->andWhere($where);
      }
      return $categories->all();
    }, $cache->defaultDuration, $dependency);
    return $categories;
  }

  /**
   * @return mixed
   */
  public static function getActiveStoresCoupons($categoryId = false)
  {
    $languages = self::languagesArray();
    $cache = Yii::$app->cache;
    $cacheName = 'stores_coupons'.($categoryId ? '_'.$categoryId : '');
    $dependencyName = 'catalog_coupons';
    $dependency = new yii\caching\DbDependency;
    $dependency->sql = 'select `last_update` from `cw_cache` where `name` = "' . $dependencyName . '"';

    $stores = $cache->getOrSet($cacheName, function () use ($categoryId, $languages) {
      $stores =  self::find()
          ->from(self::tableName() . ' cwc')
          ->select(['cws.name', 'cws.uid', 'cws.route', 'cws.is_offline', 'count(cwc.uid) as count'])
          ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
          ->where(['cws.is_active' => [0, 1]])
          ->andWhere(['>', 'cwc.date_end', date('Y-m-d H:i:s', time())])
          ->groupBy('cwc.store_id')
          ->orderBy('cws.name ASC')
          ->asArray();
      if ($categoryId) {
          $stores->innerJoin('cw_coupons_to_categories cctc', 'cwc.coupon_id = cctc.coupon_id')
              ->andWhere(['cctc.category_id' => $categoryId]);
      }
      if (!empty($languages)) {
            $stores->andWhere(['cwc.language' => $languages]);
      }
      return $stores->all();
    }, $cache->defaultDuration, $dependency);
    return $stores;
  }

  public static function activeCount($filter = '')
  {
    $languages = self::languagesArray();
    $cache = Yii::$app->cache;
    $cacheName = 'total_all_coupons' . ($filter ? '_' . $filter : '');
    $dependencyName = 'catalog_coupons';
    $dependency = new yii\caching\DbDependency;
    $dependency->sql = 'select `last_update` from `cw_cache` where `name` = "' . $dependencyName . '"';

    $count = $cache->getOrSet($cacheName, function () use ($filter, $languages) {
      $result = self::find()
          ->from(self::tableName() . ' cwc')
          ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
          //->where(['cws.is_active' => [0, 1]]);
          ->where(['cws.is_active' => [1]]);
      //фильтры
      if ($filter == 'expired') {
        $result->andWhere(['<=', 'cwc.date_end', date('Y-m-d H:i:s', time())]);
      } elseif ($filter == 'new') {
        $result->andWhere(['>', 'cwc.date_start', date('Y-m-d H:i:s', time() - 60 * 60 * 24 * self::NEW_COUPONS_SUB_DAYS)]);
      } else {
        $result->andWhere(['>', 'cwc.date_end', date('Y-m-d H:i:s', time())]);
      }
      if (!empty($languages)) {
          $result->andWhere(['cwc.language' => $languages]);
      }
      return $result->count();
    }, $cache->defaultDuration, $dependency);
    return $count;
  }

  public function afterSave($insert, $changedAttributes)
  {
    $this->clearCache();
  }

  public static function counts($store = false, $category = false)
  {
    $languages = self::languagesArray();
    $cache = \Yii::$app->cache;
    $cacheName = 'coupons_counts' . ($store ? '_' . $store : '') . ($category ? '_' . $category : '');
    $dependencyName = 'coupons_counts';
    $dependency = new yii\caching\DbDependency;
    $dependency->sql = 'select `last_update` from `cw_cache` where `name` = "' . $dependencyName . '"';
    $data = $cache->getOrSet($cacheName, function () use ($store, $category, $languages) {
      $coupons = self::find()
          ->from(self::tableName() . ' cwc')
          ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
          //->where(['cws.is_active' => [0, 1]]);
          ->where(['cws.is_active' => [1]]);
      if ($store) {
        $coupons = $coupons->andWhere(['cws.uid' => $store]);
      }
      if ($category) {
        $coupons = $coupons
            ->innerJoin('cw_coupons_to_categories cctc', 'cctc.coupon_id = cwc.coupon_id')
            ->andWhere(['cctc.category_id' => $category]);
      }
      if (!empty($languages)) {
            $coupons->andWhere(['cwc.language' => $languages]);
      }
      $all = $coupons->count();
      $coupons2 = clone $coupons;
      $expired = $coupons->andWhere(['<', 'cwc.date_end', date('Y-m-d H:i:s', time())])->count();
      $actual = $coupons2->andWhere(['>', 'cwc.date_end', date('Y-m-d H:i:s', time())])->count();

      return [
          'all' => $all,
          'expired' => $expired,
          'actual' => $actual,
      ];
    }, $cache->defaultDuration, $dependency);

    return $data;
  }

  public static function forList($as_array = true)
  {
    $languages = self::languagesArray();
    $coupons = Coupons::find()
        ->from(Coupons::tableName() . ' cwc')
        ->select(['cwc.*', 'cws.name as store_name', 'cws.route as store_route', 'cws.is_active as store_is_active',
            'cws.currency as store_currency', 'cws.displayed_cashback as store_cashback',
            'cws.action_id as store_action_id', 'cws.logo as store_image'])
        ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid');
    if (!empty($languages)) {
          $coupons->andWhere(['cwc.language' => $languages]);
    }

    if ($as_array) {
      return $coupons->asArray();
    } else {
      return $coupons;
    }
  }

  /** топ купонов
   * @param array $options
   * @return mixed
   */
  public static function top($options = [])
  {
    $languages = self::languagesArray();
    $limit = isset($options['limit']) ? $options['limit'] : 8;
    $new = isset($options['new']) ? $options['new'] : false;
    $offline = isset($options['offline']) ? $options['offline'] : false;
    $category = isset($options['category']) ? $options['category'] : false;
    $store_category = isset($options['store_category']) ? $options['store_category'] : false;
    $store = isset($options['store']) ? $options['store'] : false;
    $unique_store = isset($options['unique_store']) ? $options['unique_store'] : false;

    $cache = Yii::$app->cache;
    $cacheName = 'coupons_top_limit_' . $limit .
        ($category ? '_category_' . $category : '') .
        ($store_category ? '_store_category_' . $store_category : '') .
        ($store ? '_store_' . $store : '') .
        ($new ? '_new' : '') .
        ($offline ? '_offline' : '') .
        ($unique_store ? '_unique_store' : '');
    $dependencyName = 'coupons_counts';
    $dependency = new yii\caching\DbDependency;
    $dependency->sql = 'select `last_update` from `cw_cache` where `name` = "' . $dependencyName . '"';

    $data = $cache->getOrSet($cacheName, function () use ($limit, $category, $store_category, $store, $new, $unique_store, $offline, $languages) {

      if ($store_category && !$category) {
        //есть категория шопов и нет категорий купонов - тащим второе из первого
        $categoryCoupons = StoresCategoriesToCouponsCategories::find()
            ->where(['store_category_id' => $store_category])
            ->select('coupon_category_id')
            ->asArray()
            ->all();
        if (!empty($categoryCoupons)) {
            $category = array_column($categoryCoupons, 'coupon_category_id');
        }
      }

      if ($unique_store) {
        $coupons = self::find()
            ->alias('cwc')
            ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
            ->where(['cws.is_active' => [1]])
            ->groupBy('cwc.store_id')
            ->select(['cwc.store_id', 'visit' => 'max(cwc.visit)'])
            ->orderBy(['visit' => SORT_DESC]);
          if (!empty($languages)) {
              $coupons->andWhere(['cwc.language' => $languages]);
          }
      } else {
          $coupons = self::forList()
              //->where(['cws.is_active' => [0, 1]]);
              ->andWhere(['cws.is_active' => [1]]);
          if ($store) {
              $coupons = $coupons->andWhere(['cws.uid' => $store]);
          }
          if ($new) {
              $coupons->andWhere(['>', 'cwc.date_start', date('Y-m-d H:i:s', time() - 60 * 60 * 24 * 30)]);
          }
      }

      $coupons = $coupons->andWhere(['>', 'cwc.date_end', date('Y-m-d H:i:s', time())]);

      if ($category) {
          //или по категории купонов
        $coupons = $coupons
            ->innerJoin('cw_coupons_to_categories cctc', 'cctc.coupon_id = cwc.coupon_id')
            ->andWhere(['cctc.category_id' => $category]);
      } elseif ($store_category) {
          //если нет, то по категории шопов
        $coupons = $coupons
            ->innerJoin('cw_stores_to_categories cstc', 'cstc.store_id = cwc.store_id')
            ->andWhere(['cstc.category_id' => $store_category]);
      }

      if ($offline!==false) {
        $coupons = $coupons
            ->andWhere(['cws.is_offline' => $offline]);
      }

      if ($unique_store) {
        $coupons = self::forList()
            //->where(['cws.is_active' => [0, 1]])
            ->andWhere(['cws.is_active' => [1]])
            ->rightJoin(['cwc_top' => $coupons], 'cwc_top.store_id=cwc.store_id AND cwc_top.visit = cwc.visit');
      }

      return $coupons->limit($limit)->orderBy(['cwc.visit' => SORT_DESC])->all();

    }, $cache->defaultDuration, $dependency);

    return $data;
  }

  public static function makeOrUpdate($coupon)
  {
      $where = empty($coupon['promoCode']) ? ['store_id' => $coupon['store_id'], 'coupon_id' => $coupon['coupon_id']] : [
          'or',
          ['store_id' => $coupon['store_id'], 'coupon_id' => $coupon['coupon_id']],
          ['name' => $coupon['name'], 'promocode' => $coupon['promocode']],
      ];
      $result = ['new' => false];
      $dbCoupon = Coupons::find()->where($where)->one();
      if (!$dbCoupon) {
          $result['new'] = true;
          $dbCoupon = new Coupons;
          $dbCoupon->store_id = $coupon['store_id'];
          $dbCoupon->coupon_id = $coupon['coupon_id'];
          $dbCoupon->date_start = empty($coupon['date_start']) ? date('Y-m-d 00:00:00') : $coupon['date_start'];
          $dbCoupon->date_end = empty($coupon['date_exprire']) ?
              date('Y-m-d H:i:s', PHP_INT_SIZE == 4 ? PHP_INT_MAX : PHP_INT_MAX>>32) :
              $coupon['date_exprire'];
          $dbCoupon->promocode = empty($coupon['promocode']) ? '' : (string) $coupon['promocode'];
          $dbCoupon->description = empty($coupon['description']) ? null : $coupon['description'];
          $dbCoupon->species = 0;
          $dbCoupon->exclusive = empty($coupon['exclusive']) ? 0 : $coupon['exclusive'];;
      }
      $dbCoupon->name = $coupon['name'];
      $dbCoupon->cpa_id = $coupon['cpa_id'];
      $dbCoupon->goto_link = $coupon['link'];
      $dbCoupon->date_start = empty($coupon['date_start']) ? $dbCoupon->date_start : $coupon['date_start'];
      $dbCoupon->date_end = empty($coupon['date_expire']) ? $dbCoupon->date_end : $coupon['date_expire'];
      $dbCoupon->promocode = empty($coupon['promocode']) ? $dbCoupon->promocode : $coupon['promocode'];
      $dbCoupon->description = empty($coupon['description']) ? $dbCoupon->description : $coupon['description'];

      $result['coupon'] = $dbCoupon;
      $result['status'] = $dbCoupon->save();

      if ($result['status'] && !empty($coupon['categories'])) {
        if($coupon['cpa_id']==1){
          //Добавляем категорию в массив
          foreach ($coupon['categories'] as $categorie) {
            //Проверяем наличии купона в категории
            if(!CouponsToCategories::findOne(['coupon_id' => $dbCoupon->uid, 'category_id' => $categorie['id']])) {
              //если в базе нет категории - создаем
              if (!CategoriesCoupons::findOne(['uid' => $categorie['id']])) {
                $cat = new CategoriesCoupons();
                $cat->uid = $categorie['id'];
                $cat->name = $categorie['name'];
                $cat->route = Help::str2url($categorie['name']);
                $cat->save();
              }
              $coupon_cat = new CouponsToCategories();
              $coupon_cat->coupon_id = $dbCoupon->uid;
              $coupon_cat->category_id = $categorie['id'];
              $coupon_cat->save();
            }
          }
        }else {
          //загрузка категорий для прочих CPA
          foreach ($coupon['categories'] as $category) {
            $couponToCategory = CouponsToCategories::findOne(['coupon_id' => $dbCoupon->uid, 'category_id' => $category]);
            if (!$couponToCategory) {
              $couponToCategory = new CouponsToCategories();
              $couponToCategory->coupon_id = $dbCoupon->uid;
              $couponToCategory->category_id = $category;
              $couponToCategory->save();
            }
          }
        }

      }
      return $result;

  }

  public function getCpaName()
  {
    $cpa=$this->cpa;
    if(!$cpa)return "-";
    return $cpa->name;
  }

  public function getCpa()
  {
    return $this->hasOne(Cpa::className(), ['id' => 'cpa_id']);
  }
    /** все возможные языки для запроса
     * @param $languages
     * @return array
     */
  protected static function languagesArray()
  {
      if (empty(\Yii::$app->params['coupons_languages'])) {
          return [];
      }
      $result = [];
      foreach (\Yii::$app->params['coupons_languages'] as $language) {
          if (!empty(Yii::$app->params['coupons_languages_arrays'][$language])) {
              $result = array_merge($result, Yii::$app->params['coupons_languages_arrays'][$language]);
          }
      }
      return $result;
  }

  protected function clearCache()
  {
    //зависимости
    Cache::clearName('catalog_coupons');
    Cache::clearName('catalog_coupons_count');
    Cache::clearName('store_coupons_store');
    Cache::clearName('coupons_counts');
    Cache::clearName('stores_abc');

    //ключи
    Cache::deleteName('total_all_coupons');
    Cache::deleteName('total_all_coupons_expired');
    Cache::deleteName('total_all_coupons_new');
    //Cache::deleteName('stores_coupons');
    Cache::deleteName('categories_coupons');
    Cache::deleteName('popular_stores_with_promocodes');
  }
  
  


}
