<?php
/**
 * Created by PhpStorm.
 * User: max
 * Date: 04.12.18
 * Time: 15:33
 */

/*Yii::$app->queue->push(new MailerJob([
    'from'=>[Yii::$app->params['adminEmail'] => Yii::$app->params['adminName']]
]));*/

namespace common\components;

use console\jobs\MailerJob;
use frontend\modules\users\models\Users;
use yii;
use yii\base\Component;

use yii\di\Instance;
use yii\mail\MailerInterface;
use yii\queue\Queue;
use yii\mail\BaseMailer;

/**
 * Class Conversion
 * @package common\components
 */
class Mailer extends yii\swiftmailer\Mailer{

  public $mast_send = false;
  public $mailer = 'mailer';

  public function sendMessage($message)
  {
    if($this->mast_send){
      return parent::sendMessage($message); // TODO: Change the autogenerated stub
    }

    $jobConfig =  [
        'message' => $message,
        'mailer' => $this,
    ];
    return (Yii::$app->queue->push(new MailerJob($jobConfig)));/**/
  }

}