<?php

namespace b2b\modules\forms\controllers;

use frontend\modules\b2b_content\models\B2bContent;
use frontend\modules\b2b_users\models\B2bUsers;
use yii\web\Controller;
use Yii;
use b2b\modules\content;
use b2b\modules\forms\models\Regform;
use b2b\modules\forms\models\RegisterForm;

class DefaultController extends Controller
{
  private $page;

  public function beforeAction($action)
  {
    $request = Yii::$app->request;
    $pathInfo = $request->getPathInfo();
    $this->page = B2bContent::findOne(['page' => $pathInfo]);

    if ($this->page) {
      Yii::$app->view->registerMetaTag([
        'name' => 'description',
        'content' => $this->page->description,
      ]);
      Yii::$app->view->registerMetaTag([
        'name' => 'keywords',
        'content' => $this->page->keywords,
      ]);
      $this->page = $this->page->toArray();
    }

    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  public function actionRegistration()
  {
    $page=$this->page;
    $page['before_include'] = 'reg_form';
    $model = new Regform;

    $request = Yii::$app->request;
    if ($model->load($request->post())) {
      $user = new B2bUsers;

      $user->password = $model->password;
      $user->fio = $model->fio;
      $user->position = $model->position;
      $user->email = $model->email;
      $user->phone = $model->phone;
      $user->anketa = [
        'firm' => $model->firm,
        'url' => $model->url,
        'category' => $model->category,
        'region' => $model->region,
        'type' => $model->type,
        'old' => $model->old,
        'points' => $model->points,
      ];
      if ($user->save()) {
        Yii::$app->session->addFlash('info', 'Ваша заяка отправлена. В ближайшее время с Вами свяжется администратор.');
        return $this->redirect('/registration_finish');
      }
    }

    $page['model'] = $model;
    $page['reCaptcha'] = \himiklab\yii2\recaptcha\ReCaptcha::className();

    return $this->render('@app/modules/content/views/default/index', $page);
  }


  public function actionOffline()
  {
    $request = Yii::$app->request;

    $model = new RegisterForm;
    if ($request->isPost) {
      if ($model->load($request->post())) {
        $email = Yii::$app->params['registerEmailOffline'];
        $model->subject = "Подключить оффлайн магазин";
        if ($this->sendRegistration($email, $model)) {
          Yii::$app->session->addFlash('success', 'Сообщение отправлено, мы свяжемся с вами в ближайшее время.');
          return $this->redirect('/forms/finish');
        } else {
          Yii::$app->session->addFlash('err', 'Ошибка отправки формы.');
        }
      } else {
        Yii::$app->session->addFlash('err', 'Ошибка отправки формы.');
      }
    }

    $page=$this->page;
    $page['model'] = $model;
    $page['reCaptcha'] = \himiklab\yii2\recaptcha\ReCaptcha::className();
    return $this->render('registerForm', $page);
  }

  public function actionOnline()
  {
    $request = Yii::$app->request;

    $model = new RegisterForm;
    if ($request->isPost) {
      if ($model->load($request->post())) {
        $email = Yii::$app->params['registerEmail'];// : Yii::$app->params['registerEmail'];
        $model->subject = "Подключить интернет магазин";
        if ($this->sendRegistration($email, $model)) {
          Yii::$app->session->addFlash('success', 'Сообщение отправлено, мы свяжемся с вами в ближайшее время.');
          return $this->redirect('/forms/finish');
        } else {
          Yii::$app->session->addFlash('err', 'Ошибка отправки формы.');
        }
      } else {
        Yii::$app->session->addFlash('err', 'Ошибка отправки формы.');
      }
    }

    $page=$this->page;
    $page['model'] = $model;
    $page['reCaptcha'] = \himiklab\yii2\recaptcha\ReCaptcha::className();
    return $this->render('registerForm', $page);
  }

  protected function sendRegistration($mailTo, $model)
  {
    return Yii::$app->mailer->compose(
      ['html' => 'b2b-register-form-html', 'text' => 'b2b-register-form-text'],
      [
        'message' => $model->text,
        'title' => $model->subject,
        'name' => $model->name,
        'email' => $model->email,
        'phone' => $model->phone,
      ]
    )
      ->setFrom([Yii::$app->params['adminEmail'] => Yii::$app->params['adminName'] . ' robot'])
      ->setTo($mailTo)
      ->setSubject($model->subject)
      ->send();
  }
}
