<?php

namespace frontend\modules\withdraw\models;

use frontend\modules\users\models\Users;
use frontend\modules\cache\models\Cache;
use yii;

/**
 * This is the model class for table "cw_users_withdraw".
 *
 * @property integer $uid
 * @property integer $user_id
 * @property integer $process_id
 * @property string $bill
 * @property double $amount
 * @property integer $status
 * @property string $request_date
 * @property string $user_comment
 * @property string $admin_comment
 */
class UsersWithdraw extends \yii\db\ActiveRecord
{
  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'cw_users_withdraw';
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
      //$balanse=Yii::$app->user->identity->balance;
      return [
      [['user_id', 'process_id', 'bill', 'request_date', 'amount'], 'required'],
      [['process_id'], 'required', 'message'=>Yii::t('account', 'withrdaw_method_wrong')],
      [['process_id'], 'in', 'range' => [1, 2, 3, 4, 5, 6], 'message'=>Yii::t('account', 'withrdaw_choose_method')],
      [['user_id', 'process_id', 'status'], 'integer'],
      [['bill'], 'integer', 'when' => function($model) {
        return in_array($model->process_id, [1, 3, 4, 6]);
      }, 'whenClient' => "function(attribute,value){return $.inArray(parseInt($('#userswithdraw-process_id').val()), [1, 3, 4, 6])>-1;}" ],
      [['bill'], 'match', 'pattern'=> '/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/', 'when' => function($model) {
        return $model->process_id == 5;
      }, 'whenClient' => "function(attribute,value){return parseInt($('#userswithdraw-process_id').val()) == 5;}" ,
      'message' => Yii::t('account', 'withrdaw_email_wrong')],
      [['bill'], 'match', 'pattern'=> '/^R[0-9]{12}$/', 'when' => function($model) {
        return $model->process_id == 2;
      }, 'whenClient' => "function(attribute,value){return parseInt($('#userswithdraw-process_id').val()) == 2;}" ,
      'message' => Yii::t('account', 'withrdaw_webmoney_wrong')],
      [['amount'], 'number', 'min'=> 350/*, 'max' => ($balanse ? $balanse['current'] : null)*/],
      [['amount'], 'filter', 'filter' => function ($value) {
        return number_format($value, 2, ".", "");
      }],
      [['request_date'], 'safe'],
      [['user_comment', 'admin_comment'], 'string'],
      //[['bill'], 'string', 'max' => 255],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'uid' => 'ID',
      'user_id' => 'Пользователь',
      'process_id' => 'Тип',
      'bill' => Yii::t('common', 'number'),
      'amount' => Yii::t('common', 'amount'),
      'status' => 'Статус',
      'request_date' => 'Дата запроса',
      'user_comment' => 'Комментарий пользователя',
      'admin_comment' => 'Комментарий админа',
    ];
  }

  public function beforeValidate()
  {
    if (!parent::beforeValidate()) {
      return false;
    }

    if ($this->isNewRecord) {
      $this->user_id = Yii::$app->user->id;
      $this->request_date = date('Y-m-d H:i:s');
      $this->status = 1;
    }
    return true;
  }

  public function afterSave($insert, $changedAttributes)
  {
    parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

    if (
      $insert ||
      (
        isset($changedAttributes['status']) &&
        $changedAttributes['status'] != $this->status
      )
    ) {
      \Yii::$app->balanceCalc->todo([$this->user_id], 'withdraw');
    };
    Cache::clearName('account_withdrawhistory' . $this->user_id);
  }

  public function afterDelete()
  {
    Cache::clearName('account_withdrawhistory' . $this->user_id);
  }

  public function getUser()
  {
    $user=Users::findOne(['uid'=>$this->user_id]);
    return $user;
  }

  public function getProcess_name(){
    $pr=WithdrawProcess::findOne(['uid'=>$this->process_id]);
    return $pr->name;
  }

  /**
   * @param bool $userId - для пользователя или все
   * @return int|string количество неподтверждённых
   */
  public static function waitingCount($userId = false)
  {
    $count = self::find()->where(['status' => 1]);
    if ($userId) {
      $count = $count->andWhere(['user_id' => $userId]);
    }
    return $count->count();
  }
}
