<?php

namespace frontend\modules\stores\controllers;

use yii;
use frontend\components\SdController;
use frontend\modules\stores\models\Stores;
use frontend\modules\reviews\models\Reviews;
use frontend\modules\coupons\models\Coupons;
use frontend\modules\stores\models\CategoriesStores;
use frontend\components\Pagination;
use frontend\modules\slider\models\Slider;
use frontend\models\RouteChange;

class DefaultController extends SdController
{

    /**
     * @param string $id
     * @return null|yii\base\Action
     */
    public function createAction($id)
    {
        //todo stores/003/xxxx - сделать 404, и аналогично для купонов
        $request = \Yii::$app->request;
        $category = $request->get('category');
        $store = $request->get('store');
        if ($store) {
            throw new \yii\web\NotFoundHttpException;
        }
        if ($category) {
            $this->actionRedirects($category);
            exit;
        }
        if ($id) {
            //имеется action, который должен быть категорией или магазином, ищем такую
            $store = Stores::byRoute($id);
            if ($store) {
                //есть магазин
                echo $this->actionStore($store);
                exit;
            }
            $categoryStore = CategoriesStores::byRoute($id);
            if ($categoryStore) {
                //если есть категория
                \Yii::$app->params['url_mask'] = 'stores/category/'.$id;
                echo $this->actionIndex($id, $categoryStore);
                exit;
            };
            //если нет категории или магазина
            //найти в удалённых шопах
            $newRoute = RouteChange::getNew($id, RouteChange::ROUTE_TYPE_STORES);
            if ($newRoute) {
                //если есть новый роут для удалённого, делаем редирект
                $this->redirect('/stores/'.$newRoute, 301)->send();
                exit;
            };
            throw new \yii\web\NotFoundHttpException;
        }
        return parent::createAction($id); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     * @throws yii\web\NotFoundHttpException
     */
    public function actionIndex($actionId = '', $categoryStore = null)
    {
        $request = Yii::$app->request;

        $page = $request->get('page');
        $limit = $request->get('limit');
        $sort = $request->get('sort');

        $validator = new \yii\validators\NumberValidator();
        $validatorIn = new \yii\validators\RangeValidator(['range' => ['visit', 'name', 'added',
            'cashback_percent', 'cashback_summ']]);
        if (!empty($limit) && !$validator->validate($limit) ||
           !empty($sort) && !$validatorIn->validate($sort)
        ) {
            throw new \yii\web\NotFoundHttpException;
        };

        $sort = (!empty($sort)) ? $sort : Stores::$defaultSort;
        $limit = (!empty($limit)) ? $limit : $this->defaultLimit;
        $order = !empty(Stores::$sortvars[$sort]['order']) ? Stores::$sortvars[$sort]['order'] : 'DESC';

        $this->params['breadcrumbs'][] = ['label' => 'Магазины', 'url' => '/stores'];
        $storesData = [];
        if ($categoryStore) {
            //категория
            $category = $categoryStore->uid;
            $storesData['current_category'] = $categoryStore;//CategoryStores::byId($category);
            if ($storesData['current_category']->is_active == 0) {
                $this->redirect('/stores', 301)->send();
                exit;
            }
            //чтобы виджет мог получить current_category_id в main.twig
            \Yii::$app->controller->current_category_id = $category;

            $this->params['breadcrumbs'][] = [
              'label' => $storesData['current_category']->name,
              'url' => '/stores/category:' . $storesData['current_category']->uid,
            ];

            $dataBaseData = Stores::find()
                ->from(Stores::tableName() . ' cws')
                ->select([
                    'cws.*',
                    'cstc.category_id',
                    "substr(displayed_cashback, locate(' ', displayed_cashback)+1, locate('%', displayed_cashback)".
                    " - locate(' ', displayed_cashback) -1) + 0 as  cashback_percent",
                    "substr(displayed_cashback, locate(' ', displayed_cashback)+1, length(displayed_cashback)".
                    " - locate(' ', displayed_cashback) - locate('%', displayed_cashback)) + 0 as cashback_summ",
                ])
                ->innerJoin('cw_stores_to_categories cstc', 'cws.uid = cstc.store_id')
                ->where([
                    'cstc.category_id' => $category,
                    'is_active' => [0, 1],
                ])
                 ->orderBy($sort .' '.$order);
            $cacheName = 'catalog_stores_category' . '_' .$category .'_'.$page.'_'.$limit.'_'.$sort.'_'.$order;
        } else {
            //нет категории /stores
            $dataBaseData = Stores::find()
                ->select([
                    '*',
                    "substr(displayed_cashback, locate(' ', displayed_cashback)+1, locate('%', displayed_cashback)".
                    " - locate(' ', displayed_cashback) -1) + 0 as  cashback_percent",
                    "substr(displayed_cashback, locate(' ', displayed_cashback)+1, length(displayed_cashback)".
                    " - locate(' ', displayed_cashback) - locate('%', displayed_cashback)) + 0 as cashback_summ",
                ])
                ->where(['is_active' => [0, 1]])
                ->orderBy($sort .' '.$order);
            $cacheName = 'catalog_stores_'.$page.'_'.$limit.'_'.$sort.'_'.$order;
        }
        if ($page > 1) {
            $this->params['breadcrumbs'][] = 'Страница ' . $page;
        }
        if (isset($this->params['breadcrumbs'][intval(count($this->params['breadcrumbs'])) - 1]['url'])) {
            $this->params['breadcrumbs'][intval(count($this->params['breadcrumbs'])) - 1]['url'] = null;
        }

        $pagination = new Pagination(
            $dataBaseData,
            $cacheName,
            ['limit' => $limit, 'page' => $page, 'asArray' => 1]
        );

        $storesData['stores'] = $pagination->data();
        $storesData["total_v"] = $pagination->count();
        $storesData["show_stores"] = count($storesData['stores']);
        $storesData["offset_stores"] = $pagination->offset();
        $storesData["total_all_stores"] = Stores::activeCount();
        $storesData["page"] = empty($page) ? 1 : $page;
        $storesData["limit"] = empty($limit) ? $this->defaultLimit : $limit;

        $paginateParams = [
            'limit' => $this->defaultLimit == $limit ? null : $limit,
            'sort' => Stores::$defaultSort == $sort ? null : $sort,
            'page' => $page,
        ];
        $paginatePath = '/' . ($actionId ? $actionId . '/' : '') . 'stores';
        if ($pagination->pages() > 1) {
            $storesData["pagination"] = $pagination->getPagination($paginatePath, $paginateParams);
            $this->makePaginationTags($paginatePath, $pagination->pages(), $page, $paginateParams);
        }

        $storesData['sortlinks'] =
            $this->getSortLinks($paginatePath, Stores::$sortvars, Stores::$defaultSort, $paginateParams);
        $storesData['limitlinks'] =
            $this->getLimitLinks($paginatePath, Stores::$defaultSort, $paginateParams);
        
        $storesData['slider'] = Slider::get();

        return $this->render('catalog', $storesData);
    }

    /**
     * @param $id
     * @return string
     * @throws yii\web\NotFoundHttpException
     */
    private function actionStore($store)
    {
        if ($store->is_active<0) {
            $this->redirect('/stores', 301)->send();
            exit();
        }

        $contentData["current_store"] = $store;
        $contentData["current_store.description"] = htmlspecialchars_decode($store->description);

        $contentData["store_reviews"] = Reviews::byStoreId($store->uid);
        $contentData["store_rating"] = Reviews::storeRating($store->uid);

        $cache = \Yii::$app->cache;

        $dependency =  new yii\caching\DbDependency;
        $dependencyName = 'store_coupons_store';
        $dependency->sql = 'select `last_update` from `cw_cache` where `name` = "' . $dependencyName . '"';

        $coupons = $cache->getOrSet('store_coupons_store_'.$store->uid, function () use ($store) {
            $dateRange = ['>', 'cwc.date_end', date('Y-m-d H:i:s', time())];
            return Coupons::find()
              ->from(Coupons::tableName() . ' cwc')
              ->select(['cwc.*', 'cws.name as store_name', 'cws.route as store_route',
                'cws.currency as store_currency', 'cws.displayed_cashback as store_cashback',
                'cws.action_id as store_action_id', 'cws.logo as store_image'])
              ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
              ->where(['cws.uid' => $store->uid])
              ->andWhere($dateRange)
              ->orderBy(Coupons::$defaultSort . ' ' .
                (!empty(Coupons::$sortvars[Coupons::$defaultSort]['order']) ?
                  Coupons::$sortvars[Coupons::$defaultSort]['order'] : 'ASC'))
              ->asArray()
              ->all();
        }, $cache->defaultDuration, $dependency);
        $contentData["store_coupons"] = $coupons;
        $contentData["coupons_counts"] = Coupons::counts($store->uid);
        $contentData["all_coupons_counts"] = Coupons::counts();
        $additionalStores = $this->getAdditionals($store);
        $contentData["additional_stores"] = $additionalStores['additional_stores'];
        $contentData["additional_stores_category"] = $additionalStores['additional_stores_category'];

        $contentData["curs"] = Yii::$app->conversion->options();

        return $this->render('shop', $contentData);
    }

    /**
     * Get a list of additional stores
     * @param string $route
     * @return array
     */
    private function getAdditionals($store)
    {
        //вычисляем, не пришёл ли пользователь из категории
        $referrer = \Yii::$app->request->referrer;
        $category = [];
        if ($referrer && strpos($referrer, '/stores/')) {
            $categoryRoute = explode('/', $referrer);
            foreach ($categoryRoute as $route) {
                if (preg_match('/category\:[0-9]*$/', $route)) {
                    $category[0] = substr($route, 9);
                    break;
                }
            }
        }
        //если не из категории в качестве категорий берём категории товара
        if (empty($category)) {
            $categories = $store->categories;
            foreach ($categories as $cat) {
                if ($cat->is_active == 1) {
                    $category[] = $cat->uid;
                }
            }
        }
        $cache = Yii::$app->cache;
        
        $dependency =  new yii\caching\DbDependency;
        $dependencyName = 'additional_stores';
        $dependency->sql = 'select `last_update` from `cw_cache` where `name` = "' . $dependencyName . '"';
        if (!count($category)) {
            //если нет категорий (гипотетически)
            $additional_stores = $cache->getOrSet('additional_stores_except_'.$store->uid, function () use ($store) {
                return Stores::find()
                    ->where(['is_active' => [0, 1]])
                    ->andWhere(['<>', 'uid', $store->uid])
                    ->orderBy('RAND()')
                    ->limit(6)
                    ->asArray()
                    ->all();
            }, $cache->defaultDuration, $dependency);
        } else {
           //категория есть или одна или много
            $additional_stores = $cache->getOrSet(
                'additional_stores_by_categories_' . implode('_', $category) . '_except_' . $store->uid,
                function () use ($category, $store
                ) {
                    return Stores::find()
                        ->from(Stores::tableName() . ' cws')
                        ->select(['cws.*'])
                        ->innerJoin('cw_stores_to_categories cwstc', 'cws.uid = cwstc.store_id')
                        ->where(['cws.is_active' => [0, 1], 'cwstc.category_id' => $category])
                        ->andWhere(['<>', 'cws.uid', $store->uid])
                        ->orderBy('RAND()')
                        ->limit(6)
                        ->asArray()
                        ->all();
                },
                $cache->defaultDuration,
                $dependency
            );
            $additional_stores_category = CategoriesStores::byId($category[0]);
        };
        return [
            'additional_stores' => $additional_stores,
            'additional_stores_category' => empty($additional_stores_category) ? null : $additional_stores_category,
        ];
    }

    /**
     * @param $store
     * @throws \yii\web\NotFoundHttpException
     * из маршрутизации "по-старому" перенаправления на "по-новому"
     */
    public function actionRedirects($store)
    {
        $parent = CategoriesStores::byId($store);
        if (!$parent || $parent->is_active == 0) {
            throw new \yii\web\NotFoundHttpException;
        }
        $this->redirect('/stores/'.$parent->route, 301)->send();
        exit;
    }


}

