<?php

namespace frontend\modules\stores\controllers;

use yii;
use frontend\components\SdController;
use frontend\modules\stores\models\Stores;
use frontend\modules\reviews\models\Reviews;
use frontend\modules\coupons\models\Coupons;
use frontend\modules\category_stores\models\CategoryStores;
use frontend\components\Pagination;

class DefaultController extends SdController
{

    /**
     * @param string $id
     * @return null|yii\base\Action
     */
    public function createAction($id)
    {
        $parent = parent::createAction($id); // TODO: Change the autogenerated stub
        if ($parent) {
            return $parent;
        } else {
            echo $this->actionStore($id);
            exit;
        }
    }

    /**
     * @return string
     * @throws yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;

        $page = $request->get('page');
        $limit = $request->get('limit');
        $sort = $request->get('sort');
        $category = $request->get('category');

        $validator = new \yii\validators\NumberValidator();
        $validatorIn = new \yii\validators\RangeValidator(['range' => ['visit', 'name', 'added',
            'cashback_percent', 'cashback_summ']]);
        if (!empty($limit) && !$validator->validate($limit) ||
           !empty($page) && !$validator->validate($page) ||
           !empty($category) && !$validator->validate($category) ||
           !empty($sort) && !$validatorIn->validate($sort)
        ) {
            throw new \yii\web\NotFoundHttpException;
        };

        $sort = (!empty($sort)) ? $sort : Stores::$defaultSort;
        $limit = (!empty($limit)) ? $limit : $this->defaultLimit;
        $order = !empty(Stores::$sortvars[$sort]['order']) ? Stores::$sortvars[$sort]['order'] : 'DESC';


        $storesData = [];
        if (!empty($category)) {
            //категория
            $storesData['current_category'] = CategoryStores::find()->where(['uid' => $category])->one();
            if ($storesData['current_category'] == null) {
                throw new \yii\web\NotFoundHttpException;
            }
            if ($storesData['current_category']->is_active == 0) {
                return $this->redirect('/stores', 301);
            }
            $dataBaseData = Stores::find()
                ->from(Stores::tableName() . ' cws')
                ->select([
                    'cws.*',
                    'cstc.category_id',
                    "substr(displayed_cashback, locate(' ', displayed_cashback)+1, locate('%', displayed_cashback)".
                    " - locate(' ', displayed_cashback) -1) + 0 as  cashback_percent",
                    "substr(displayed_cashback, locate(' ', displayed_cashback)+1, length(displayed_cashback)".
                    " - locate(' ', displayed_cashback) - locate('%', displayed_cashback)) + 0 as cashback_summ",

                ])
                ->innerJoin('cw_stores_to_categories cstc', 'cws.uid = cstc.store_id')
                ->where([
                    'cstc.category_id' => $category,
                    'is_active' => [0, 1],
                ])
                 ->orderBy($sort .' '.$order);
            $cacheName = 'catalog_stores_category' . '_' .$category .'_'.$page.'_'.$limit.'_'.$sort.'_'.$order;
        } else {
            //нет категории /stores
            $dataBaseData = Stores::find()
                ->select([
                    '*',
                    "substr(displayed_cashback, locate(' ', displayed_cashback)+1, locate('%', displayed_cashback)".
                    " - locate(' ', displayed_cashback) -1) + 0 as  cashback_percent",
                    "substr(displayed_cashback, locate(' ', displayed_cashback)+1, length(displayed_cashback)".
                    " - locate(' ', displayed_cashback) - locate('%', displayed_cashback)) + 0 as cashback_summ",

                ])
                ->where(['is_active' => [0, 1]])
                ->orderBy($sort .' '.$order);
            $cacheName = 'catalog_stores_'.$page.'_'.$limit.'_'.$sort.'_'.$order;
        }
        $pagination = new Pagination(
            $dataBaseData,
            $cacheName,
            ['limit' => $limit, 'page' => $page, 'asArray' => 1]
        );

        $storesData['stores'] = $pagination->data();
        $storesData["total_v"] = $pagination->count();
        $storesData["show_stores"] = count($storesData['stores']);
        $storesData["offset_stores"] = $pagination->offset();
        $storesData["total_all_stores"] = Stores::activeCount();
        $storesData["page"] = empty($page) ? 1 : $page;
        $storesData["limit"] = empty($limit) ? $this->defaultLimit : $limit;

        $paginateParams = [
            'category' => $category,
            'limit' => $this->defaultLimit == $limit ? null : $limit,
            'sort' => Stores::$defaultSort == $sort ? null : $sort,
            'page' => $page,
        ];
        if ($pagination->pages() > 1) {
            $storesData["pagination"] = $pagination->getPagination($request->pathInfo, $paginateParams);
            $this->makePaginationTags($request->pathInfo, $pagination->pages(), $page, $paginateParams);
        }

        $storesData['sortlinks'] =
            $this->getSortLinks($request->pathInfo, Stores::$sortvars, Stores::$defaultSort, $paginateParams);
        $storesData['limitlinks'] =
            $this->getLimitLinks($request->pathInfo, Stores::$defaultSort, $paginateParams);

        return $this->render('catalog', $storesData);
    }

    /**
     * @param $id
     * @return string
     * @throws yii\web\NotFoundHttpException
     */
    private function actionStore($id)
    {
        $validator = new \yii\validators\StringValidator();
        if (!$validator->validate($id)) {
            throw new \yii\web\NotFoundHttpException;
        }
        $store = Stores::byRoute($id);
        if (!$store) {
            throw new \yii\web\NotFoundHttpException;
        }
        $contentData["current_store"] = $store;
        $contentData["current_store.description"] = htmlspecialchars_decode($store->description);

        $contentData["store_reviews"] = Reviews::byStoreId($store->uid);

        $cache = \Yii::$app->cache;
        $coupons = $cache->getOrSet('store_coupons_store_'.$id, function () use ($store) {
            return Coupons::find()
                ->from(Coupons::tableName(). ' cwc')
                ->select(['cwc.*', 'cws.name as store_name', 'cws.route as store_route',
                    'cws.currency as store_currency', 'cws.displayed_cashback'])
                ->innerJoin(Stores::tableName() . ' cws', 'cwc.store_id = cws.uid')
                ->where(['cws.is_active' => [0, 1], 'cws.uid' => $store->uid])
                ->orderBy(Coupons::$defaultSort)
                ->asArray()
                ->all();
        });
        $contentData["store_coupons"] = $coupons;

//
//        $this->contentData["store_rating"] = $this->getStoreRating($reviewsContentData["reviews"]);

//        $additionalStores = $this->getAdditionalStores($route, $store->uid);
//        $this->contentData["additional_stores"] = $additionalStores['additional_stores'];
//        $this->contentData["additional_stores_category"] = $additionalStores['additional_stores_category'];

        //d($contentData);



        return $this->render('shop', $contentData);
    }

}

