<?php

namespace frontend\modules\constants\models;

use frontend\modules\ar_log\behaviors\ActiveRecordChangeLogBehavior;
use Yii;

/**
 * This is the model class for table "cw_constants".
 *
 * @property integer $uid
 * @property string $name
 * @property string $title
 * @property string $text
 * @property string $ftype
 * @property string $updated_at
 */
class Constants extends \yii\db\ActiveRecord
{
    public static $categories = [
        0 => 'Остальное',
        1 => 'Стартовая',
        2 => 'Аккаунт',
        3 => 'Шопы',
        4 => 'Купоны',
        5 => 'Списки',
        6 => 'Ссылки',
        7 => 'Системные',
        8 => 'Региональные',
        9 => 'Каталог'
    ];

  protected static $translated_attributes = ['text'];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cw_constants';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'title', 'ftype'], 'required'],
            [['name', 'title', 'ftype'], 'trim'],
            [['text'], 'string'],
            [['text'], 'trim'],
            [['updated_at'], 'safe'],
            [['name', 'title', 'ftype'], 'string', 'max' => 255],
            //[['editor_param'], 'string', 'max' => 255],
            [['name'], 'unique'],
        ];
    }



  public function behaviors()
  {
    return [
        [
            'class' => ActiveRecordChangeLogBehavior::className(),
        ],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
        'uid' => 'Uid',
        'name' => 'Name',
        'title' => 'Title',
        'text' => 'Text',
        'ftype' => 'Ftype',
        'updated_at' => 'Updated At',
    ];
  }

    /**
     * @return \yii\db\ActiveQuery
     */
  public function getLanguages()
  {
      return $this->hasMany(LgConstants::className(), ['const_id' => 'uid']);
  }

  public function afterFind()
  {
    if ($this->ftype == 'json' && is_string($this->text)) {
      $this->text = json_decode($this->text, true);
    }
    parent::afterFind(); // TODO: Change the autogenerated stub
  }

    public function beforeValidate()
    {
      if(isset($this->text)) {
        if(isset($this->oldAttributes['ftype'])) {
          $this->ftype = $this->oldAttributes['ftype'];
        };
        if ($this->ftype == 'json' && is_array($this->text)) {
          $this->text = json_encode($this->text);
        }
      }
      return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * категории для фильтра
     * @return array
     */
    public static function categoryList()
    {
        $categories = self::find()
            ->select(['category', 'count(*) as count'])
            ->groupBy('category')
            ->asArray()
            ->orderBy(['category' => SORT_DESC])
            ->all();
        $result = [];
        foreach ($categories as $category) {
            $result[] = [
               'link' => '/admin/constants?ConstantsSearch[category]='.$category['category'],
               'name' =>  isset(self::$categories[$category['category']]) ?
                       self::$categories[$category['category']] : $category['category'],
               'count' => $category['count'],
            ];
        }
        $result[] = [
            'link' => '/admin/constants',
            'name' =>  'Все',
            'count' => self::find()->count(),
        ];
        return $result;
    }

    /**
     * @param $name
     * @param bool $json_col
     * @param int $json_index
     * @return mixed
     */
    public static function byName($name, $json_col = false, $json_index = 0)
    {

        $language = Yii::$app->language  == Yii::$app->params['base_lang'] ? false : Yii::$app->language;
        $cash_name = $name . '_' . $json_col . '_' . $json_index
            . ($language ? '_' . $language : '')
            . (Yii::$app->params['region'] != 'default' ? '_' . Yii::$app->params['region'] : '');

        return Yii::$app->cache->getOrSet($cash_name, function () use ($name, $json_col, $json_index, $language) {
            $const = self::find()->from(self::tableName() . ' cwc')->where(['name' => $name])->asArray();
            if ($language) {
                $const->select(['if(lgc.text > "" and cwc.has_lang=1, lgc.text, cwc.text) as text', 'ftype', 'category'])
                    ->leftJoin(
                        LgConstants::tableName() . ' lgc',
                        'lgc.const_id = cwc.uid and lgc.language="'.$language.'"'
                    );
            } else {
                $const->select(['text', 'ftype', 'category']);
            }
            $const = $const->one();
            if ($const) {
                if ($const['ftype'] == 'json' && is_string($const['text'])) {
                    $const['text'] = json_decode($const['text'], true);
                }
                if ($const['category'] == 8) {
                    //региональные,
                    $json_index = array_search($json_index, array_column($const['text'], 'code'));
                    $json_col = Yii::$app->params['region'];
                    if ($json_index === false) {
                        return false;
                    }
                }
                if ($json_col !== false) {
                    if (isset($const['text'][$json_index])) {
                        if (is_array($const['text'][$json_index]) && isset($const['text'][$json_index][$json_col])) {
                            return ['text' => $const['text'][$json_index][$json_col], 'ftype' => $const['ftype']];
                        } else {
                            if ($const['category'] == 8) {
                                //можно только значение, не массив
                                return false;
                            }
                            return ['text' => $const['text'][$json_index], 'ftype'=> $const['ftype']];
                        }
                    } else {
                        return false;
                    }
                }
                return ['text'=> $const['text'], 'ftype' => $const['ftype']];
            } else {
                return false;
            }
        });
    }
}
