<?php

namespace frontend\modules\constants\models;

use frontend\modules\ar_log\behaviors\ActiveRecordChangeLogBehavior;
use Yii;


/**
 * This is the model class for table "lg_constants".
 *
 * @property integer $uid
 * @property integer $const_id
 * @property string $language
 * @property string $text
 *
 * @property CwConstants $const
 */
class LgConstants extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lg_constants';
    }

  public function behaviors()
  {
    return [
        [
            'class' => ActiveRecordChangeLogBehavior::className(),
        ],
    ];
  }

  public function formName()
  {
    return 'Const_'.$this->language;
  }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['const_id', 'language'], 'required'],
            [['text'], 'required', 'enableClientValidation'=> false],
            [['const_id'], 'integer'],
            [['text'], 'string'],
            [['language'], 'string', 'max' => 10],
            [['const_id', 'language'], 'unique', 'targetAttribute' => ['const_id', 'language'], 'message' => 'The combination of Const ID and Language has already been taken.'],
            [['const_id'], 'exist', 'skipOnError' => true, 'targetClass' => Constants::className(), 'targetAttribute' => ['const_id' => 'uid']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'uid' => 'Uid',
            'const_id' => 'Const ID',
            'language' => 'Language',
            'text' => 'Text',
        ];
    }

    public function getConstant()
    {
        return $this->hasOne(Constants::className(), ['uid' => 'const_id']);
    }

    public function beforeValidate()
    {
        if (isset($this->text)) {
            $type = $this->constant->ftype;
            if ($type == 'json' && is_array($this->text)) {
                $editorParamRules = realpath(__DIR__ .'/../') .
                    '/views/admin/json/'.$this->constant->editor_param.'_rules.json';
                if (file_exists($editorParamRules)) {
                    $rules = json_decode(file_get_contents($editorParamRules), true);
                    foreach ($this->text as $textItem) {
                        foreach ($textItem as $attr => $value) {
                            if (isset($rules[$attr]) && $rules[$attr] == 'required' && trim($value) == '') {
                                Yii::$app->session->addFlash('err', $this->formName() . ' задан пустой атрибут '.$attr);
                            }
                        }
                    }
                }
                $this->text = json_encode($this->text);
            }
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        if ($this->constant->ftype == 'json' && is_string($this->text)) {
            $this->text = json_decode($this->text, true);
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConst()
    {
        return $this->hasOne(CwConstants::className(), ['uid' => 'const_id']);
    }
}
