<?php

namespace frontend\components\socials;

use yii\base\Object;

class Google extends \nodge\eauth\services\GoogleOAuth2Service
{

  const SCOPE_BIRTH_DAY = 'https://www.googleapis.com/auth/user.birthday.read';

  public $info;
  //protected $scopes = [self::SCOPE_USERINFO_PROFILE, self::SCOPE_USERINFO_EMAIL, self::SCOPE_BIRTH_DAY];
  protected $scopes = [self::SCOPE_USERINFO_PROFILE, self::SCOPE_USERINFO_EMAIL];

  public function init($data = false)
  {
    parent::init(); // TODO: Change the autogenerated stub
    if(!$data)return;
    if(isset($data['info']))$this->info=$data['info'];
  }

  protected function fetchAttributes()
  {
    $info = $this->info?$this->info:$this->makeSignedRequest('https://www.googleapis.com/oauth2/v1/userinfo');
    $info = json_decode(json_encode($info), true);

    $this->attributes['social_name'] = isset($this->name)?$this->name:$info['source'];
    $this->attributes['social_id'] = strval($info['id']);
    $this->attributes['name'] = isset($info['displayName'])?$info['displayName']:$info['name'];

    $this->attributes['url'] = (!empty($info['link'])) ? $info['link'] : null;

    $this->attributes['email'] = !empty($info['email']) ? $info['email'] : null;
    if(isset($info['emails'])){
      foreach ($info['emails'] as $email) {
        if (!empty($email['value'])) {
          $this->attributes['email']=$email['value'];
          break;
        }
      }
    }

    $this->attributes['photo'] = !empty($info['picture']) ? $info['picture'] : null;
    if(isset($info['image']) && !empty($info['image']['url'])){
      $this->attributes['photo'] = $info['image']['url'];
    }

    $this->attributes['sex'] = empty($info['gender']) ? null :
      ($info['gender'] == 'female' ? 'f' : ($info['gender'] == 'male' ? 'm' : null));
    $this->attributes['birthday'] = !empty($info['birthday']) ?
      date('Y-m-d', strtotime($info['birthday'])) :
      null;

    //ddd($info, $this->attributes);
  }

  public function getAttributes(){
    $this->fetchAttributes();
    return $this->attributes;
  }
}
