<?php
return  [
  'default'=>[
    'layout'=>'main.twig',
    'js'=>[
      '/js/jquery-1.11.2.min.js',
      '/js/scripts{{script_version}}.js',
      '/js/external/jquery.mCustomScrollbar.concat.min.js',
      '//ulogin.ru/js/ulogin.js',
    ],
    'css'=>[
         '/css/external/import.fonts.css',
         '/css/external/animate.min.css',
         'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css',
         '/css/external/jquery.mCustomScrollbar.min.css',
         '/css/external/popup.css',
         '/css/styles{{script_version}}.css',
    ],
  ],
  'account'=>[
      'layout'=>'account.twig',
      'js'=>[
        '/js/jquery-2.1.4.js',
        '/js/account/scripts{{script_version}}.js',
        '/js/external/jquery.mCustomScrollbar.concat.min.js',
        '/js/external/account/modernizr.js'
      ],
      'css'=>[
        '/css/external/import.fonts.css',
        '/css/external/animate.min.css',
        'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css',
        '/css/external/jquery.mCustomScrollbar.min.css',
        '/css/external/popup.css',
        '/css/account/styles{{script_version}}.css',
      ]
  ],
  'admin'=>[
      'layout'=>'admin.twig',
      'js'=>[
        //'/js/jquery-2.1.4.js',
        '/js/admin/scripts{{script_version}}.js',
        '/js/external/jquery.mCustomScrollbar.concat.min.js',
        '/js/external/account/modernizr.js'
      ],
      'css'=>[
        '/css/external/import.fonts.css',
        'https://fonts.googleapis.com/css?family=Open+Sans:300,400,700',
        'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css',
        '/css/admin/styles{{script_version}}.css',
      ]

  ]
];