<?php

namespace frontend\modules\b2b_users\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use frontend\modules\b2b_users\models\B2bUsers;

/**
 * B2bUsersSearch represents the model behind the search form about `frontend\modules\b2b_users\models\B2bUsers`.
 */
class B2bNewUsers extends B2bUsers{

  public function rules()
  {
    $rules=parent::rules(); // TODO: Change the autogenerated stub
    $rules[]=[['password'], 'required'];
    return $rules;
  }
}