<?php

namespace frontend\modules\b2b_users\models;

use Yii;

/**
 * This is the model class for table "b2b_users".
 *
 * @property integer $id
 * @property string $email
 * @property string $first_name
 * @property string $last_name
 * @property integer $city
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email_confirm_token
 * @property string $auth_key
 * @property string $created_at
 * @property string $login_at
 * @property string $ip
 */
class B2bUsers extends \yii\db\ActiveRecord
{
  public $password;

  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'b2b_users';
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['email', 'fio'], 'required'],
      [['email'], 'email'],
      [['is_active'], 'number'],
      [['email'], 'unique', 'message' => 'Данныей email принадлежит другому пользователю.'],
      [['password','email'], 'trim'],
      [['fio','position','email','phone','anketa'],'safe'],
      [['password'], 'string', 'max' => 60],
      [['password'], 'string', 'min' => 5],
      [['created_at', 'login_at'], 'safe'],
      [['email'], 'string', 'max' => 255],
      [['password_hash', 'password_reset_token', 'email_confirm_token'], 'string', 'max' => 60],
      [['auth_key'], 'string', 'max' => 32],
      [['ip'], 'string', 'max' => 20],
    ];
  }

  public function afterFind()
  {
    if($this->anketa && strlen($this->anketa)) {
      $this->anketa = json_decode($this->anketa, true);
    }else{
      $this->anketa=false;
    }
  }

  public function beforeValidate()
  {

    if(is_array($this->anketa)) {
      $this->anketa = json_encode($this->anketa);
    }

    if (!parent::beforeValidate()) {
      return false;
    }

    if ($this->isNewRecord) {
      //$this->reg_ip = $_SERVER["REMOTE_ADDR"];
      $this->created_at = date('Y-m-d H:i:s');

      if (!isset($this->auth_key)) {
        $this->auth_key = '';
      }
    }

    if ($this->password) {
      $this->setPassword($this->password);
    }
    return true;

  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'email' => 'Email',
      'password' => 'Пароль',
      'password_hash' => 'Password Hash',
      'password_reset_token' => 'Password Reset Token',
      'email_confirm_token' => 'Email Confirm Token',
      'auth_key' => 'Auth Key',
      'created_at' => 'Создан',
      'login_at' => 'Последний вход',
      'ip' => 'Ip',
      'fio' => 'Ф.И.О.',
      'position' => 'Должность',
      'phone' => 'Телефон',
      'is_active' => 'Статус',
    ];
  }

  /**
   * Generates password hash from password and sets it to the model
   *
   * @param string $password
   */
  public function setPassword($password)
  {
    $this->password = $password;
    $this->password_hash = Yii::$app->security->generatePasswordHash($password);
  }

  public function beforeDelete()
  {

    UsersCpa::deleteAll(['user_id' => $this->id]);

    return parent::beforeDelete(); // TODO: Change the autogenerated stub
  }

  public function getStringActive()
  {
    $status = [
      0=>"В ожидании",
      1=>"Отклонён",
      2=>"Подтвержден",
    ];
    return $status[$this->is_active];
  }
}
