<?php

namespace frontend\modules\b2b_users\models;

use frontend\modules\stores\models\CpaLink;
use frontend\modules\stores\models\Stores;
use Yii;

/**
 * This is the model class for table "b2b_users_cpa".
 *
 * @property integer $id
 * @property integer $cpa_link_id
 * @property integer $user_id
 * @property integer $created_at
 */
class UsersCpa extends \yii\db\ActiveRecord
{
  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'b2b_users_cpa';
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['cpa_link_id', 'user_id', 'created_at'], 'required'],
      [['cpa_link_id', 'user_id', 'created_at'], 'integer'],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'cpa_link_id' => 'Cpa Link ID',
      'user_id' => 'User ID',
      'created_at' => 'Created At',
    ];
  }

  public function getCpaStore()
  {
    return $this->hasOne(CpaLink::className(), ['id' => 'cpa_link_id'])
    //return CpaLink::findOne(['id' => $this->cpa_link_id])
;
  }

  public function beforeValidate()
  {
    if ($this->isNewRecord) {
      $this->created_at = time();
    };
    return parent::beforeValidate(); // TODO: Change the autogenerated stub
  }
}
