<?php

namespace frontend\modules\slider\models;

use Yii;
use frontend\modules\stores\models\Stores;
use JBZoo\Image\Image;

/**
 * This is the model class for table "cw_promo_stores".
 *
 * @property integer $uid
 * @property string $title
 * @property string $description
 * @property string $date_start
 * @property string $date_end
 * @property integer $type
 * @property string $json
 * @property string $image
 * @property string $show_as
 * @property integer $is_showed
 */
class Slider extends \yii\db\ActiveRecord
{
  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'cw_slider';
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['title', 'date_start', 'date_end',], 'required'],
      [['json'], 'string'],
      [['date_start', 'date_end'], 'safe'],
      [['is_showed','sort_index'], 'integer'],
      [['title'], 'string', 'max' => 255]
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'uid' => 'Uid',
      'title' => 'Название',
      'description' => 'Описание',
      'date_start' => 'Date Start',
      'date_end' => 'Date End',
      'type' => 'Type',
      'json' => 'json',
      'image' => 'Image',
      'show_as' => 'Отображать',
      'is_showed' => 'Is Showed',
      'sort_index' => 'Порядок сортировки'
    ];
  }

  public function afterFind()
  {
    if(strlen($this->json)<3){
      $this->json="		{
			fon:'/images/slides/test/header_bg.jpg',
			mobile:'/images/slides/test/maxresdefault-4-1.jpg',
			paralax:[
				{
					img:'/images/slides/test/drops_bg_back.png',
					z:1,
				},
				{
					img:'/images/slides/test/drops_bg_up.png',
					z:2,
				},
				{
					img:'/images/slides/test/text_uretiyoruz_bg.png',
					pos:2,
					z:3,
				},
				{
					img:'/images/slides/test/text_vesonra_bg.png',
					pos:8,
					z:4,
				},
			],
			fixed:[],
			button:{
				pos:8,
				href:'/',
				color:'bordo',
				text:'Перейти',
        show_delay:3,
        show_animation:'rollIn',
        hide_delay:0,
        hide_animation:'hinge',
			}
		}";
    }
    parent::afterFind(); // TODO: Change the autogenerated stub
  }

  /**
   * Getting a list of
   * store promotions
   */
  public static function get()
  {
    return Yii::$app->cache->getOrSet('slider', function () {
      $queryResult = self::find()
        ->from(self::tableName() . " cwps")
        ->select(["*"])
        ->where(["cwps.is_showed" => 1])
        ->orderBy(['sort_index'=>SORT_ASC])
        ->asArray()
        ->all();
      return $queryResult;
    });
  }


  function beforeSave($insert)
  {
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

}
