<?php

namespace frontend\modules\slider\models;

use frontend\modules\ar_log\behaviors\ActiveRecordChangeLogBehavior;
use Yii;
use frontend\modules\stores\models\Stores;
use JBZoo\Image\Image;

/**
 * This is the model class for table "cw_promo_stores".
 *
 * @property integer $uid
 * @property string $title
 * @property string $description
 * @property string $date_start
 * @property string $date_end
 * @property integer $type
 * @property string $json
 * @property string $image
 * @property string $show_as
 * @property integer $is_showed
 */
class Slider extends \yii\db\ActiveRecord
{

  static $def_slide="{
			fon:'/images/slides/test/header_bg.jpg',
			mobile:'/images/slides/test/maxresdefault-4-1.jpg',
			paralax:[
				{
					img:'/images/slides/test/drops_bg_back.png',
					z:1,
				},
				{
					img:'/images/slides/test/drops_bg_up.png',
					z:2,
				},
				{
					img:'/images/slides/test/text_uretiyoruz_bg.png',
					pos:2,
					z:3,
				},
				{
					img:'/images/slides/test/text_vesonra_bg.png',
					pos:8,
					z:4,
				},
			],
			fixed:[],
			button:{
				pos:8,
				href:'/',
				color:'bordo',
				text:'Перейти',
        show_delay:3,
        show_animation:'rollIn',
        hide_delay:0,
        hide_animation:'hinge',
			}
		}";

  private $places_array = [
      'index' => ['name' => 'Стартовая. залогиненый'],
      'online-shop' => ['name' => 'Шопы-онлайн'],
      'offline-shop' => ['name' => 'Шопы-оффлайн'],
      'product' => ['name' => 'Товары. Стартовая'],
  ];
  public $regions_array = [];
  public $slide_places = [];
  public $slide_regions = [];

  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'cw_slider';
  }

  public function behaviors()
  {
    return [
        [
            'class' => ActiveRecordChangeLogBehavior::className(),
          //'ignoreAttributes' => ['visit','rating'],
        ],
    ];
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['title', 'date_start', 'date_end',], 'required'],
      [['json','place','lang','region'], 'string'],
      [['date_start', 'date_end'], 'safe'],
      [['is_showed','sort_index'], 'integer'],
      [['title','place','lang','region'], 'string', 'max' => 255],
      [['slide_places'], 'in', 'allowArray' => true, 'range' => array_keys($this->getPlaces_array())],
      [['slide_regions'], 'in', 'allowArray' => true, 'range' => array_keys(Yii::$app->params['regions_list'])],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'uid' => 'Uid',
      'title' => 'Название',
      'description' => 'Описание',
      'date_start' => 'Date Start',
      'date_end' => 'Date End',
      'type' => 'Type',
      'json' => 'json',
      'image' => 'Image',
      'show_as' => 'Отображать',
      'is_showed' => 'Is Showed',
      'sort_index' => 'Порядок сортировки',
      'lang' => 'Язык',
      'region' => 'Регионы'
    ];
  }

  public function afterFind()
  {
    if(strlen($this->json)<20){
      $this->json=Slider::$def_slide;
    }
    $places = !empty($this->place) ? explode(',', $this->place) : [];
    foreach ($this->places_array as $key => $value) {
      $this->places_array[$key]['checked'] = in_array($key, $places) ?  1 : 0;
    }

    $regions = !empty($this->region) ? explode(',', $this->region) : [];

    foreach (Yii::$app->params['regions_list'] as $key => $value) {
        $this->regions_array[] = [
            'code' => $key,
            'name' => $value['name'],
            'checked' => in_array($key, $regions) ? 1 : 0
        ];
    }
    parent::afterFind(); // TODO: Change the autogenerated stub
  }

  public function beforeValidate()
  {
    if (!parent::beforeValidate()) {
      return false;
    }
    $this->slide_places = method_exists(Yii::$app->request, 'post') &&
    isset(Yii::$app->request->post('Slider')['slide_places']) ?
        Yii::$app->request->post('Slider')['slide_places'] : null ;
    if ($this->slide_places) {
      $this->place = implode(',', $this->slide_places);
    }
    if ($this->slide_regions) {
      $this->region = implode(',', $this->slide_regions);
    }
    return true;
  }

  /**
   * Getting a list of
   * store promotions
   */
  public static function get($params=[])
  {
    $place = !empty($params['place']) ? $params['place'] : false;
    if(is_string($place))
      $place=explode(',',$place);

    if(is_array($place)){
      foreach ($place as &$item) $item=trim($item);
    }
    
    $region=Yii::$app->params['region'];
    $lg=Yii::$app->language;

    $cash_name='slider_'.$region.'_'.$lg.($place ? '_' . implode(',',$place) : '');
    return Yii::$app->cache->getOrSet($cash_name, function ()  use ($place,$region,$lg) {
      $queryResult = self::find()
          ->from(self::tableName() . " cwps")
          ->select(["json"]);

      if ($place) {
        foreach ($place as $item)
          $queryResult->orWhere(['like', 'place', $item]);
      }

      $date=date('Y-m-d G:i:s');
      $queryResult=$queryResult
          ->andWhere(['like', 'region', $region])
          ->andWhere(['=', 'lang', $lg])
          ->andWhere(["cwps.is_showed" => 1])
          ->andWhere(['<','date_start',$date])
          ->andWhere(['>','date_end',$date])
          ->orderBy(['sort_index' => SORT_ASC])
          ->asArray()
          ->all();

      $out = [];
      foreach ($queryResult as $item) {
        if(strlen($item['json'])<3){
          $item['json']=Slider::$def_slide;
        }
        $out[] = $item['json'];
      }
      return $out;
    });
  }

  function beforeSave($insert)
  {
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function getPlaces_array(){
    $places_array=$this->places_array;
    return $places_array;
  }

}
