<?php

namespace frontend\modules\users\controllers;

use common\components\Help;
use frontend\components\socials\Google;
use frontend\modules\users\models\UsersSocial;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;


class SocialController extends Controller
{

  private $url = false;
  private $urlCancel = false;

  public function actions()
  {
    return [
        'socials-auth' => [
            'class' => 'yii\authclient\AuthAction',
            'successCallback' => [$this, 'onAuthSuccess'],
        ],
    ];
  }

  public function init()
  {
    $this->url = Yii::$app->getUser()->getReturnUrl();
    if (strpos($this->url, 'g=plugin') !== false || strlen($this->url) < 3) {
      $this->url = null;
    }
    $this->urlCancel = Yii::$app->getUrlManager()->createAbsoluteUrl(Help::href('site/login'));
    parent::init(); // TODO: Change the autogenerated stub
  }

  public function actionSocials()
  {
    $serviceName = Yii::$app->getRequest()->getQueryParam('service');
    $serviceName = $serviceName ? $serviceName : ($this->serviceName ? $this->serviceName : null);
    //ddd($serviceName);
    if (isset($serviceName)) {
      /** @var $eauth \nodge\eauth\ServiceBase */
      $eauth = Yii::$app->get('eauth')->getIdentity($serviceName);

      $eauth->setRedirectUrl($this->url);
      $eauth->setCancelUrl($this->urlCancel);
      //ddd($eauth);
      try {
        if ($eauth->authenticate()) {

          //ddd($eauth);
          //получаем юсера нашего
          $user = UsersSocial::authenticate($eauth->getAttributes());

          self::testUser($user, $eauth);
          // special redirect with closing popup window
          $eauth->redirect();
        } else {
          // close popup window and redirect to cancelUrl
          $eauth->cancel();
        }
      } catch (\nodge\eauth\ErrorException $e) {
        // save error to show it later
        Yii::$app->getSession()->setFlash('error', 'EAuthException: ' . $e->getMessage());

        // close popup window and redirect to cancelUrl
//              $eauth->cancel();
        $eauth->redirect($eauth->getCancelUrl());
      }
    } else {
      throw new NotFoundHttpException();
    }
    // default authorization code through login/password .
  }


  public function onAuthSuccess($client)
  {
    $attributes = $client->getUserAttributes();
    $r = [
        'source' => $client->getId() == "google" ? "google_oauth" : $client->getId(),
        'source_id' => $attributes['id'],
    ];

    $attributes['source'] = $client->getId() == "google" ? "google_oauth" : $client->getId();
    switch ($r['source']) {
      case "google_oauth":
        $attr = new Google(['info' => $attributes]);
        break;
    }
    $attr = $attr->getAttributes();

    $user = UsersSocial::authenticate($attr);

    self::testUser($user);
  }

  private function testUser($user, $eauth = false)
  {
    //ddd($user);
    if (!empty($user)) {
      if (!Yii::$app->user->isGuest) {
        if ($eauth) {
          $eauth->redirect(Help::href('/account/settings'));
        } else {
          Yii::$app->response->redirect(Help::href('/account/settings'));
          return;
        }
      }

      Yii::$app->user->login($user);
      //$this->redirect(['/account' . ((time() - strtotime($user->added) < 60) ? '?new=1' : '')])->send();
      $url = Yii::$app->user->getReturnUrl();
      //$url = explode('//',$url);
      //$url=$url[count($url)-1];
      $url = str_replace(Yii::$app->request->getHostInfo(), '', $url);

      if (strpos($url, 'g=plugin') !== false) $url = null;
      if (strlen($url) < 3) {
        $url = null;
      }
      $url=(!empty($url) ? $url : Help::href('/account' . ((time() - strtotime($user->added) < 60) ? '?new=1' : '')));
      if ($eauth) {
        $eauth->redirect($url);
      } else {
        Yii::$app->response->redirect($url);
      }
      return;
    } else {
      if ($eauth) {
        $eauth->redirect($this->urlCancel);
      } else {
        Yii::$app->response->redirect($this->urlCancel);
      }
    }
  }
}
