<?php

namespace api\controllers;

use Yii;
use yii\web\Controller;

class DataController extends Controller
{
  public function beforeAction($action)
  {
    if (Yii::$app->user->isGuest) {
      //$user = Users::findOne(8);
      //Yii::$app->user->login($user);
      throw new \yii\web\NotFoundHttpException("not found.");
      return;
    }
    return parent::beforeAction($action); // TODO: Change the autogenerated stub
  }

  public function actionSystem()
  {
    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

    $params = Yii::$app->params;

    $data = [
        'loyalty_status'=>$params['dictionary']['loyalty_status'],
        'language_list'=>$params['language_list'],
    ];
    //ddd(Yii::$app->params, $data);
    return $data;
  }
}