<?php

namespace api\controllers;

class SiteController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        d($action);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        return 'index';
    }


}
