<?php

namespace frontend\modules\transitions\models;

use Yii;
use frontend\modules\stores\models\Stores;
use frontend\modules\users\models\Users;
use frontend\modules\cache\models\Cache;
use frontend\modules\stores\models\CpaLink;

/**
 * This is the model class for table "cw_users_visits".
 *
 * @property integer $uid
 * @property integer $user_id
 * @property integer $source
 * @property string $visit_date
 * @property integer $store_id
 * @property string $user_ip
 */
class UsersVisits extends \yii\db\ActiveRecord
{
   const TRANSITION_TYPE_STORE = 0;
   const TRANSITION_TYPE_COUPON = 1;
   const TRANSITION_TYPE_PARTHNER = 2;
   const TRANSITION_TYPE_PARTHNER_CHECK_COOKIE = 3;
   const TRANSITION_TYPE_PRODUCTS = 4;
   const TRANSITION_TYPE_PRODUCTS_CATALOG = 5;

    /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'cw_users_visits';
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['user_id', 'visit_date'], 'required'],
      [['user_id', 'source', 'store_id', 'product_id'], 'integer'],
      [['visit_date'], 'safe'],
      [['referrer'], 'string', 'max' => 256],
      [['user_ip'], 'string', 'max' => 16],
      [['user_agent'], 'string'],
    ];
  }

  /**
  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'uid' => 'Uid',
      'user_id' => 'User ID',
      'subid' => 'Sub ID',
      'source' => 'Source',
      'visit_date' => 'Visit Date',
      'store_id' => 'Store ID',
      'user_ip' => 'User Ip',
      'user_agent' => 'User Agent',
      'referrer' => 'Referrer',
      'cpa_name' => 'Cpa',
    ];
  }

  public function getCpaLink()
  {
      return $this->hasOne(CpaLink::className(), ['id' => 'cpa_link_id']);
  }

  public function beforeValidate()
  {
    if (!parent::beforeValidate()) {
      return false;
    }

    if ($this->isNewRecord) {
      $this->user_ip = Yii::$app->request->getUserIP();
      $this->visit_date = date('Y-m-d H:i:s');
      $this->user_agent =Yii::$app->request->getUserAgent();
      $this->referrer = Yii::$app->request->getReferrer();
      if (empty($this->user_id)) {
        $this->user_id = (Yii::$app->user->isGuest ? 0 : Yii::$app->user->id);
      }
    }
    return true;

  }

  public function beforeSave($insert)
  {

    if ($this->isNewRecord) {
      $shop = Stores::findOne(['uid' => $this->store_id]);
      $shop->visit += 1;
      $shop->save();
    }

    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }

  public function afterSave($insert, $changedAttributes)
  {
    Cache::clearName('account_transitions' . $this->user_id);
    Cache::clearName('stores_visited');
    if (isset(Yii::$app->params['regions_list'][Yii::$app->params['region']]['langList'])) {
      foreach (Yii::$app->params['regions_list'][Yii::$app->params['region']]['langList'] as $language) {
        $lang = $language == Yii::$app->params['base_lang'] ? '' : $language . '_';
        //Cache::deleteName('products_viewed_by_user_' . $lang . $this->user_id);
        Cache::deleteName('products_viewed_by_user_' . $lang . 'limit_100_'.$this->user_id);//просмотренные товары много
        Cache::deleteName('products_viewed_by_user_' . $lang . 'limit_4_'.$this->user_id);//просмотренные товары мало
        Cache::deleteName('products_viewed_by_user_' . $lang . 'count_'.$this->user_id);//просмотренные товары количество

      }
    }
  }

  public function afterDelete()
  {
    Cache::clearName('account_transitions' . $this->user_id);
  }

  public function getStore()
  {
    return $this->hasOne(Stores::className(), ['uid' => 'store_id']);
  }

  public function getUser()
  {
    return $this->hasOne(Users::className(), ['uid' => 'user_id']);
  }

    /** количество переходов по отлеживаемым шопам за отслеживаемое время
     * @return int|string
     */
  public static function watchedCount()
  {
      return self::find()
          ->innerJoin(Stores::tableName(), Stores::tableName() . '.uid = ' . self::tableName() . '.store_id')
          ->where(['watch_transitions' => 1])
          ->andWhere(['>=', 'visit_date', date('Y-m-d 00:00:00', time())])
          ->count();
  }

}
