<?php
namespace b2b\components;

use frontend\modules\favorites\models\UsersFavorites;
use Yii;
use yii\web\View;
use yii\helpers\Url;
use yii\twig\ViewRenderer;

class SdView extends View
{

  public $all_params=[];
  public $first_init= true;


  public function init_param()
  {
    $this->first_init=false;

    $request = Yii::$app->request;

    if ($request->isAjax) {
      return ;
    }

  }

  public function render($view, $params = [], $context = null)
  {
    if($this->first_init){
      $this->init_param();
    }
    if(!is_array($params)) {
      $params=$params->toArray();
    }
    $this->all_params=array_merge($this->all_params,$params);
    if($this->all_params && isset($this->all_params['exception'])){
      Yii::$app->params['exception'] = $this->all_params['exception'];
    };
    Yii::$app->params['all_params']=$this->all_params;
    $this->writeOgMetatags();

    return parent::render($view, $this->all_params, $context); // TODO: Change the autogenerated stub
  }

  public function renderAjax($view, $params = [], $context = null)
  {
    if($this->first_init){
      $this->init_param();
    }
    $this->all_params=array_merge($this->all_params,$params);
    Yii::$app->params['all_params']=$this->all_params;
    return parent::renderAjax($view, $this->all_params, $context); // TODO: Change the autogenerated stub
  }


  public function afterRender($viewFile, $params, &$output){
    parent::afterRender($viewFile, $params, $output); // TODO: Change the autogenerated stub
    //ddd($this->all_params);
    //Проставление переменных только когда рендорится слой layout
    if(
      strpos($viewFile,'layout')>0
    ) {
      $output=Yii::$app->TwigString->render(
        $output,
        $this->all_params
      );
    }
  }

  /**
   *og: метатеги, пишем те, которых нет
   */
  protected function writeOgMetatags()
  {
    $tags = [];
    foreach (Yii::$app->view->metaTags as $meta) {
      if (strpos($meta, 'property="')) {
        $tags[] = substr($meta, strpos($meta, 'property="') + 10, strpos($meta, '" ') - strpos($meta, 'property="') - 10);
      }
    }

    if (!in_array('og:url', $tags)) {
      Yii::$app->view->metaTags[]='<meta property="og:url" content="https://b2b.secretdiscounter.ru/' .
        \Yii::$app->request->pathInfo.'" />';
    }
    if (!in_array('og:title', $tags) && isset($this->all_params['title'])) {
      Yii::$app->view->metaTags[]='<meta property="og:title" content="'.$this->all_params['title'].'" />';
    }
    if (!in_array('og:description', $tags) && isset($this->all_params['description'])) {
      Yii::$app->view->metaTags[]='<meta property="og:description" content="'.$this->all_params['description'].'" />';
    }
    if (!in_array('og:image', $tags)) {
      Yii::$app->view->metaTags[]='<meta property="og:image" content="https://secretdiscounter.ru/images/templates/woman_600.png" />';
    }
  }
}