<?php

namespace console\controllers;

use common\models\Doubletrade;
use frontend\modules\actions\models\ActionsActions;
use frontend\modules\coupons\models\Coupons;
use frontend\modules\payments\models\Payments;
use frontend\modules\stores\models\Cpa;
use frontend\modules\stores\models\CpaLink;
use frontend\modules\stores\models\Stores;
use frontend\modules\users\models\Users;
use JBZoo\Image\Image;
use Yii;
use yii\console\Controller;
use yii\helpers\Console;

class DoublertradeController extends Controller
{
  private $cpa_id;
  private $stores;
  private $affiliate_list;
  private $records;
  private $inserted;
  private $fails;
  private $updated;
  private $insertedCpaLink;
  private $failsCpaLink;
  private $users;
  private $failsNotStore;
  private $failsNotUser;

  public function init()
  {
    $cpa = Cpa::find()->where(['name' => 'Doublertrade'])->one();
    if (!$cpa) {
      echo 'Cpa type Doublertrade not found';
      return;
    }
    $this->cpa_id = $cpa->id;
    parent::init(); // TODO: Change the autogenerated stub
  }

  public function beforeAction($action)
  {
    if (Console::isRunningOnWindows()) {
      shell_exec('chcp 65001');
    }
    return parent::beforeAction($action);
  }

  public function actionTest()
  {
    $service = new DoubleTrade();

    ddd($service->categories());
  }

  /**
   * получение шопов из DoublerTrade
   * @throws \yii\db\Exception
   */
  public function actionOffers()
  {
    $service = new DoubleTrade();

    $offers = $service->offers();

    if (isset($offers['matrix']['rows']['row'])) {
      foreach ($offers['matrix']['rows']['row'] as $store) {
        $cashback = is_array($store['programTariffAmount']) ? '' : ($store['programTariffAmount'] . (string)($store['isPercentage'] == 'yes' ? '%' : ''));
        if (!isset($this->stores[$store['AdvertiserWebsite']]) && $store['status'] == "Accepted") {
          $this->stores[$store['AdvertiserWebsite']] = $store;
        }
        if ($cashback != "" && isset($this->stores[$store['AdvertiserWebsite']])) {
          $this->stores[$store['AdvertiserWebsite']]['cashbacks'][] = [
              'display' => $cashback,
              'amount' => $store['programTariffAmount']
          ];
        }
      }
      foreach ($this->stores as $store) {
        $this->writeStore($store);
      }
    }
    if (!empty($affiliate_list)) {
      $sql = "UPDATE `cw_stores` cws
            LEFT JOIN cw_cpa_link cpl on cpl.cpa_id=" . $this->cpa_id . " AND cws.`active_cpa`=cpl.id
            SET `is_active` = '0'
            WHERE cpl.affiliate_id NOT in(" . implode(',', $affiliate_list) . ") AND is_active!=-1";
      Yii::$app->db->createCommand($sql)->execute();
    }
    echo 'Stores ' . count($this->stores) . "\n";
    echo 'Inserted ' . $this->inserted . "\n";
    if (!empty($this->fails)) {
      echo 'Errors ' . $this->fails . "\n";
    }
    echo 'InsertedCpaLink ' . $this->insertedCpaLink . "\n";
    if (!empty($this->failsCpaLink)) {
          echo 'Errors ' . $this->failsCpaLink . "\n";
    }

  }

  public function actionVouchers()
  {

    $inserted = 0;

    $service = new DoubleTrade();

    $vouchers = $service->vouchers();
    foreach ($vouchers as $voucher) {
      $store = $this->getStore($voucher['programId']);
      if (!$store) {
        echo 'Store ' . $voucher['programId'] . ' not found' . "\n";
        continue;
      }
      $coupon = [
          'store_id' => $store->uid,
          'coupon_id' => $voucher['id'],
          'name' => $voucher['title'],
          'description' => $voucher['shortDescription'] .
              ($voucher['description'] == $voucher['shortDescription'] ? '' : ' ' . $voucher['description']),
          'promocode' => $voucher['code'] == 'НЕ ТРЕБУЕТСЯ' ? '' : $voucher['code'],
          'date_start' => date('Y-m-d H:i:s', (int)$voucher['startDate'] / 1000),
          'date_expire' => date('Y-m-d H:i:s', (int)$voucher['endDate'] / 1000),
          'link' => $voucher['defaultTrackUri'],
          'cpa_id' => $this->cpa_id,
          'exclusive' => (bool)$voucher['exclusive'] ? 1 : 0,
      ];
        $result = Coupons::makeOrUpdate($coupon);
        if ($result['new'] && $result['status']) {
            $inserted++;
        }
        if (!$result['status']) {
            d($coupon, $result['coupon']->errors);
        }
    }
    echo "Coupons " . count($vouchers) . "\n";
    echo "Inserted " . $inserted . "\n";
  }

  public function actionOrders()
  {
    $pay_status = [
      //пока со всем этим непонятно
        "Auto-approve" => 2,
    ];


    $service = new DoubleTrade();

    $conversions = $service->conversions();
    if (isset($conversions['matrix']['rows']['row'])) {
      foreach ($conversions['matrix']['rows']['row'] as $row) {
        $this->records++;
        d($row);
        $store = $this->getStore($row['programId']);
        if (!$store) {
          $this->failsNotStore++;
          continue;
        }
        //$user = $this->getUser(8);
        $user = $this->getUser((int)$row['epi1']);
        if (!$user) {
          $this->failsNotUser++;
          continue;
        }
        $date = date('Y-m-d H:i:s', strtotime($row['timeOfEvent']));
        $status = isset($pay_status[$row['pendingRule']]) ? $pay_status[$row['pendingRule']] : 0;
        $id = substr(str_replace('_', '', $row['orderNR']), -9);
        $payment = [
            'cpa_id' => $this->cpa_id,
            'affiliate_id' => $row['programId'],
            'subid' => $user->uid,
            'action_id' => $id,
            'status' => $status,
            'ip' => null,
            'currency' => $store->currency,//Валюта платежа
            'cart' => $row['orderValue'],  //Сумма заказа в валюте
            'payment' => $row['affiliateCommission'],  //комиссия в валюте магазина
            'click_date' => $date,
            'action_date' => $date,
            'status_updated' => $date,
            'closing_date' => $row['validon'],
            'order_id' => (String)$row['orderNR'],
            "tariff_id" => null,
        ];
        $paymentStatus = Payments::makeOrUpdate(
            $payment,
            $store,
            $user,
            $user->referrer_id ? $this->getUser($user->referrer_id) : null,
            ['notify' => true, 'email' => true]
        );

        if ($paymentStatus['save_status']) {
          if ($paymentStatus['new_record']) {
            $this->inserted++;
          } else {
            $this->updated++;
          }
        } else {
          d($paymentStatus['payment']->errors);
        }

      }
      //делаем пересчет бланса пользователей
      if (count($this->users) > 0) {
        $users = array_keys($this->users);
        Yii::$app->balanceCalc->setNotWork(false);
        Yii::$app->balanceCalc->todo($users, 'cash,bonus');

        try {
          ActionsActions::observeActions($users);
        } catch (\Exception $e) {
          d('Error applying actions ' . $e->getMessage());
        }
      }
    }
    echo 'Payments ' . $this->records . "\n";
    echo 'Inserted ' . $this->inserted . "\n";
    echo 'Updated ' . $this->updated . "\n";
    if ($this->failsNotStore) {
      echo 'Stores not found ' . $this->failsNotStore . "\n";
    }
    if ($this->failsNotUser) {
      echo 'Users not found ' . $this->failsNotUser . "\n";
    }

  }

  private function writeStore($store)
  {
    $status = $store['status'] == "Accepted" ? 1 : 0;
    $cashback = $this->maxCashback($store['cashbacks']);

    $affiliate_id = $store['programId'];
    $this->affiliate_list[] = $affiliate_id;
    $newStore = [
        'logo' => (string)$store['logo'],
        'cpa_id' => $this->cpa_id,
        'affiliate_id' => $affiliate_id,
        'url' => (string) $store['AdvertiserWebsite'],
        'name' => (string) $store['programName'],
        'currency' => (string) $store['programTariffCurrency'],
        'cashback' => $cashback,
        'hold_time' => $store['pendingPeriod'],
        'status' => $status,
        'affiliate_link' => (string) $store['trackingURL'],

    ];
      $result = Stores::addOrUpdate($newStore);

      if (!$result['result']) {
          $this->fails++;
      }
      if ($result['new']) {
          $this->inserted++;
      }
      if ($result['newCpa']) {
          $this->insertedCpaLink++;
          if (!$result['resultCpa']) {
              $this->failsCpaLink++;
          }
      }
  }

  private function maxCashback($cashbacks)
  {
    $amount = 0;
    $display = 0;
    foreach ($cashbacks as $cashback) {
      if ($cashback['amount'] > $amount) {
        $display = $cashback['display'];
        $amount = $cashback['amount'];
      }
    }
    $value = (float) preg_replace('[^0-9\,\.]', '', $display) / 2;
    $display = $value . (strpos($display, '%') !== false ? '%' : '');
    $display = (count($cashbacks) > 1 ? 'до ' : '') . $display;
    return $display;
  }

  private function getStore($affiliateId)
  {
    if (!isset($this->stores[$affiliateId])) {
      $cpaLink = CpaLink::findOne(['cpa_id' => $this->cpa_id, 'affiliate_id' => $affiliateId]);
      if ($cpaLink) {
        $this->stores[$affiliateId] = $cpaLink->store;
      } else {
        $this->stores[$affiliateId] = false;
      }
    }
    return $this->stores[$affiliateId];
  }

  private function getUser($userId)
  {
    if (!isset($this->users[$userId])) {
      $user = Users::findOne(['uid' => $userId]);
      $this->users[$userId] = $user ? $user : false;
    }
    return $this->users[$userId];
  }


}