<?php
namespace shop\components;

use common\components\SdViewBASE;
use Yii;
use yii\web\View;
use yii\helpers\Url;
use yii\twig\ViewRenderer;
use frontend\modules\payments\models\Payments;
use shop\modules\category\models\ProductsCategory;

class SdView extends SdViewBASE
{

  protected $metaClass = 'frontend\modules\meta\models\CatMeta';

  public $sd_counter = false;
  public $product_main_category = false;


  public function init_param()
  {
    $this->first_init=false;

    $request = Yii::$app->request;
    if ($request->isAjax) {
      return ;
    }
  }

  public function render($view, $params = [], $context = null)
  {
    if($this->first_init){
      $this->init_param();
    }
    $this->type='shop';
    if(!is_array($params)) {
      $params=$params->toArray();
    }
    $this->all_params=array_merge($this->all_params,$params);
    if($this->all_params && isset($this->all_params['exception'])){
      Yii::$app->params['exception'] = $this->all_params['exception'];
    };
    Yii::$app->params['all_params']=$this->all_params;

    if (isset(Yii::$app->request->get()['g']) && Yii::$app->request->get()['g']=='ajax_load') {
      Yii::$app->controller->layout = '@app/views/layouts/ajax_load.twig';
          //return parent::renderAjax($view, $this->all_params, $context);
    }
    if ($this->sd_counter == false) {
        $this->sd_counter = Payments::counter();
    }
    if ($this->product_main_category == false) {
      // Потребляет дофига ресурсов!!!!!
      /// //$this->product_main_category = ProductsCategory::top(['parent' => null, 'count' => 20]);
    }

    return parent::render($view, $this->all_params, $context); // TODO: Change the autogenerated stub
  }

  public function renderAjax($view, $params = [], $context = null)
  {
    if($this->first_init){
      $this->init_param();
    }
    $this->all_params=array_merge($this->all_params,$params);
    Yii::$app->params['all_params']=$this->all_params;
    return parent::renderAjax($view, $this->all_params, $context); // TODO: Change the autogenerated stub
  }


  public function afterRender($viewFile, $params, &$output){
    parent::afterRender($viewFile, $params, $output); // TODO: Change the autogenerated stub
    //ddd($this->all_params);
    //Проставление переменных только когда рендорится слой layout
    if(
      strpos($viewFile,'layout')>0
    ) {
      $output=Yii::$app->TwigString->render(
        $output,
        $this->all_params
      );
    }
  }
}